const PRODUCTS = [
  {
    "asin": "B0DYVNRG3B",
    "title": "Celular Samsung Galaxy A36 5G 128GB, 6GB RAM, Câmera 50MP, IP67, Super AMOLED 6.7\", Recursos AI, Branco",
    "image": "https://m.media-amazon.com/images/I/613Vrz+GcaL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1449.0,
    "price_original": 2699.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2478,
    "coupon_code": null,
    "description": "<ul><li>Feito para Durar: até 6 atualizações de Android e Segurança</li><li>Tela imersiva de 6.7\" Super AMOLED com Vision Booster</li><li>Resistente à água e poeira com IP67</li><li>Câmera com recursos de AI e Nightography / Circule para Pesquisar no Google</li><li>Bateria de 5000 mAh e carregamento rápido de até 45W</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Sistema operacional": "Android 15.0",
      "Tamanho instalado da memória RAM": "6 GB",
      "Modelo da CPU": "A-Series",
      "Velocidade da CPU": "2 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Celular-Samsung-Galaxy-C%C3%A2mera-Recursos/dp/B0DYVNRG3B?ref=dlx_deals_dg_dcl_B0DYVNRG3B_dt_sl14_88_pi&pf_rd_r=10DN3TATJWP67H1P0Z02&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": true
  },
  {
    "asin": "B0FJPL1MGY",
    "title": "Samsung Galaxy Watch Ultra 2025 Smartwatch 47mm LTE, Galaxy AI, Titânio Aeroespacial, Titânio Prata",
    "image": "https://m.media-amazon.com/images/I/518YXVYcCRL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 2099.0,
    "price_original": 4999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 66,
    "coupon_code": null,
    "description": "<ul><li>Titânio Aeroespacial e resistência</li><li>Até 100m de resistencia a água do mar</li><li>Bateria de até 100h</li><li>GPS duplo de alta precisão</li><li>Treinador de corrida avançado</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "Galaxy AI",
      "Capacidade de armazenamento da memória": "64 GB",
      "Capacidade da bateria": "590 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, NFC, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Galaxy-Watch-Smartwatch-Tit%C3%A2nio/dp/B0FJPL1MGY?ref=dlx_deals_dg_dcl_B0FJPL1MGY_dt_sl14_88_pi&pf_rd_r=10DN3TATJWP67H1P0Z02&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": true
  },
  {
    "asin": "B07VRYJWPB",
    "title": "Finish Power Powder Advanced Detergente para Lava Louças em Pó 2,5kg",
    "image": "https://m.media-amazon.com/images/I/61FuIlOh2GL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 98.78,
    "price_original": 146.59,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 22494,
    "coupon_code": null,
    "description": "<ul><li>Finish Power Powder Advanced é o seu detergente lava louças em pó que oferece limpeza profunda na dose certa. Recomendado pelos principais fabricantes de lava louças do Brasil e do mundo.</li><li>Sua louça do dia a dia vai ficar limpa de primeira, sem necessidade de pré-enxague. Possui ingredientes na fórmula que promovem o cuidado e proteção das louças.</li><li>Exclusiva fórmula com oxigênio ativo e enzimas que promovem limpeza através de sua ação desengordurante e da remoção de sujeiras.</li><li>Vem com medidor que ajuda a dosar corretamente a quantidade do detergente lava louças.</li><li>Usar lava louças remove até as sujeiras mais difíceis, sem bagunça, sem ressecar as mãos. É mais qualidade de vida!</li></ul>",
    "informacoes_produto": {
      "Marca": "Finish",
      "Forma do produto": "Pó",
      "Aroma": "Sem perfume",
      "Característica do material": "Sem perfume",
      "Número de itens": "4"
    },
    "affiliate_url": "https://www.amazon.com.br/Detergente-Para-Lou%C3%A7as-Finish-Advanced/dp/B07VRYJWPB?ref=dlx_deals_dg_dcl_B07VRYJWPB_dt_sl14_88_pi&pf_rd_r=10DN3TATJWP67H1P0Z02&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0DKVJ1HWB",
    "title": "Lola Cosmetics Kit Cronograma Capilar Be(m) Dita Ghee - 3 Produtos",
    "image": "https://m.media-amazon.com/images/I/71K-GAoX50L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 38.8,
    "price_original": 69.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 6335,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/FEIRA-CRONOLOLA-Cronograma-Capilar-Produtos/dp/B0DKVJ1HWB?ref=dlx_deals_dg_dcl_B0DKVJ1HWB_dt_sl14_88_pi&pf_rd_r=10DN3TATJWP67H1P0Z02&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0C9RVFRZD",
    "title": "Duracell Pilhas Alcalinas AA Pequena Pack 24 Unidades – Dura até 10x Mais – Ideal para Controle de Videogame e Brinquedos",
    "image": "https://m.media-amazon.com/images/I/81k5RxCXI5L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 99.65,
    "price_original": 124.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 33272,
    "coupon_code": null,
    "description": "<ul><li>Pilha Duracell Alcalina AA que fornece mais duração e potência para os aparelhos</li><li>Dura mais, muito mais</li><li>Longa duração: As pilhas alcalinas AA Duracell duram mais que as pilhas comuns de zinco-carbono, oferecendo energia confiável e de alto desempenho</li><li>As pilhas Duracell podem manter sua capacidade energética por até 10 anos, mesmo sem uso, garantindo energia disponível quando você precisar</li><li>Projetadas para oferecer o melhor desempenho em dispositivos de uso diário, como brinquedos, lanternas, controles remotos e teclados</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "24 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "200",
      "Adequação do controle por rádio": "Brinquedos, Controle de videogame, Controle remoto"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilha-AA-Pequena-24-Unidades/dp/B0C9RVFRZD?ref=dlx_deals_dg_dcl_B0C9RVFRZD_dt_sl14_88_pi&pf_rd_r=10DN3TATJWP67H1P0Z02&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B000WLN7AM",
    "title": "Whisky Bourbon Maker's Mark 750ml",
    "image": "https://m.media-amazon.com/images/I/7199P9zzMGL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 119.9,
    "price_original": 145.33,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3369,
    "coupon_code": null,
    "description": "<ul><li>Com coloração âmbar, laranja-amarelada, o bourbon tornou-se um dos destilados mais apreciados no mundo.</li><li>Diferentemente da composição do whisky tradicional, o Maker’s Mark não possui centeio na sua formulação, e sim, trigo doce e vermelho de inverno, milho e cevada.</li><li>O sucesso é fruto de um processo produtivo minucioso, que segue à risca os padrões de qualidade.</li><li>A produção é feita em baixa escala, em lotes individuais que não ultrapassam 19 barris por lote.</li><li>O Maker’s Mark é envelhecido por cerca de seis anos, depois de engarrafado é então selado em uma garrafa de forma única e selada com a cera vermelha na rolha.</li></ul>",
    "informacoes_produto": {
      "Marca": "Maker's Mark",
      "Tipo de álcool": "Bourbon",
      "Sabor": "Chocolate",
      "Contagem de unidades": "750.0 Mililitro",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Whiskey-MakerS-Mark-Makers-Sabor/dp/B000WLN7AM?ref=dlx_deals_dg_dcl_B000WLN7AM_dt_sl14_88_pi&pf_rd_r=VQM25CKVFGFG48EN70E0&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H4HYLQ71",
    "title": "Notebook Gamer Lenovo Loq 15irx9, 15.6\" Full Hd 144hz, Intel Core I5-13450hx, 16gb, 512gb Ssd, Nvidia Rtx 4050, Linux - 83khs00300",
    "image": "https://m.media-amazon.com/images/I/61+CippnCvL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 5899.0,
    "price_original": 6555.54,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 6,
    "coupon_code": null,
    "description": "<ul><li>Processador estável Intel Core i5-13450HX</li><li>Tela Gamer com taxa de 144Hz</li><li>Notebook Gamer Lenovo LOQ 15IRX9 i5 16GB 512GB SSD RTX 4050 144Hz</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ 15IRX9",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "512 GB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Linux",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "49 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-15irx9-I5-13450hx-Nvidia/dp/B0H4HYLQ71?ref=dlx_deals_dg_dcl_B0H4HYLQ71_dt_sl14_88_pi&pf_rd_r=10DN3TATJWP67H1P0Z02&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": true
  },
  {
    "asin": "index-0",
    "title": "Pilha Alcalina, Elgin, Palito AAA, Blister com 4",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71faB-DYcoL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 6.66,
    "price_original": 11.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 31653,
    "coupon_code": null,
    "description": "<ul><li>Embalagem com 4 pilhas alcalinas tipo AAA Palito</li><li>Alta Durabilidade na Carga.</li><li>Composição livre de metais pesados que são prejudiciais à saúde.</li><li>Aprovadas por laboratórios credenciados pelo INMETRO.</li><li>Ideal para aparelhos que requerem descargas de energia rápidas e fortes.</li><li>As alcalinas AAA da Elgin receberam os selos Melhor do Teste e Escolha Certa da Proteste de pilhas com melhor desempenho.</li><li>Validade 5 anos.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AAA (necessita de baterias)",
      "Marca": "Elgin",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "300 Amperes Horas",
      "Adequação do controle por rádio": "Diversos"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilhas-Alcalinas-Palito-Elgin-Baterias/dp/B0754J12RW/ref=zg_bs_g_electronics_d_sccl_1/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-4",
    "title": "Pilha recarregável AAA 1000mAh Elgin com 4 unidades Palito",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71SnHLZ+XjL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 22.25,
    "price_original": 43.02,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 23240,
    "coupon_code": null,
    "description": "<ul><li>Blister Com 4 Pilhas AAA de 1000Mah.</li><li>Energia renovável de alta qualidade, as pilhas recarregáveis da Elgin suportam até 1000 recargas.</li><li>Aprovadas pelo INMETRO: As Pilhas Elgin Energy são testadas periodicamente por laboratórios credenciados pelo INMETRO, para garantir a qualidade e conformidade com a resolução Conama 401.</li><li>Ecologicamente corretas: As Pilhas da Elgin têm 0% de Mercúrio e Cadmio em sua composição, colaborando para a preservação do meio ambiente.</li><li>Indicada para brinquedos, controle de videogames e produtos de alto consumo de pilha.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AAA (necessita de baterias)",
      "Marca": "Elgin",
      "Composição das células da bateria": "NiMH",
      "Capacidade da bateria": "1000",
      "Adequação do controle por rádio": "Brinquedos"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilha-recarreg%C3%A1vel-1000mAh-unidades-Palito/dp/B0754KMGFN/ref=zg_bs_g_electronics_d_sccl_5/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-6",
    "title": "Oikos - Kit 3 Sacos para Lavar Roupas Delicadas P,M e G com Zíper | Camisetas, proteção dos tecidos, roupas íntimas, máquina de lavar, reutilizáveis",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61BJhE0GLIL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 19.9,
    "price_original": 25.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4320,
    "coupon_code": null,
    "description": "<ul><li>Com 3 tamanhos diferentes: comportam desde a roupa íntima até roupa de cama, protegendo os tecidos durante a lavagem - principalmente os mais finos e delicados.</li><li>Funcionais: eles mantêm a qualidade das peças e ainda deixam as roupas sem aquelas bolinhas e nem fiapos.</li><li>Multiusos: também são bem legais na hora de organizar a mala de viagem e para proteger aquelas roupas que não são usadas no dia a dia dentro do armário.</li><li>Acabamento no zíper: seu zíper tem um compartimento próprio para não desfiar as roupas enquanto a lavagem acontece na máquina.</li><li>Fácil de limpar: pode ser lavado normalmente na água corrente com sabão, ou na máquina de lavar.</li></ul>",
    "informacoes_produto": {
      "Marca": "OIKOS",
      "Material": "Plástico, Poliéster",
      "Cor": "Branco",
      "Dimensões do produto": "40C x 50L x 0,3A centímetros",
      "Características especiais": "Acabamento no zíper, Fácil de limpar"
    },
    "affiliate_url": "https://www.amazon.com.br/Oikos-conjunto-m%C3%A1quina-roupas-delicadas/dp/B086WWQX1S/ref=zg_bs_g_appliances_d_sccl_7/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-7",
    "title": "Oikos - Kit 3 Sacos para Lavar Roupas Delicadas P,M e G com Zíper | Camisetas, proteção dos tecidos, roupas íntimas, máquina de lavar, reutilizáveis",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61BJhE0GLIL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrodomésticos",
    "price_current": 19.9,
    "price_original": 25.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4323,
    "coupon_code": null,
    "description": "<ul><li>Com 3 tamanhos diferentes: comportam desde a roupa íntima até roupa de cama, protegendo os tecidos durante a lavagem - principalmente os mais finos e delicados.</li><li>Funcionais: eles mantêm a qualidade das peças e ainda deixam as roupas sem aquelas bolinhas e nem fiapos.</li><li>Multiusos: também são bem legais na hora de organizar a mala de viagem e para proteger aquelas roupas que não são usadas no dia a dia dentro do armário.</li><li>Acabamento no zíper: seu zíper tem um compartimento próprio para não desfiar as roupas enquanto a lavagem acontece na máquina.</li><li>Fácil de limpar: pode ser lavado normalmente na água corrente com sabão, ou na máquina de lavar.</li></ul>",
    "informacoes_produto": {
      "Marca": "OIKOS",
      "Material": "Plástico, Poliéster",
      "Cor": "Branco",
      "Dimensões do produto": "40C x 50L x 0,3A centímetros",
      "Características especiais": "Acabamento no zíper, Fácil de limpar"
    },
    "affiliate_url": "https://www.amazon.com.br/Oikos-conjunto-m%C3%A1quina-roupas-delicadas/dp/B086WWQX1S/ref=zg_bs_g_appliances_d_sccl_8/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-8",
    "title": "PHILIPS, Fone de Ouvido com Microfone, TAUE101BK/00, Com fio de 1,2 metros, intra-auricular, Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51+W7A115SL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 23.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 3516,
    "coupon_code": null,
    "description": "<ul><li>Streaming simplificado: com a plataforma de streaming para TV nº 1 dos Estados Unidos*, é fácil e divertido descobrir apps populares, além de milhares de filmes, séries, esportes e TV ao vivo. *Baseado em horas de streaming—Hypothesis Group</li><li>Transforme sua TV em uma Smart TV de verdade com o Roku Streaming Stick.</li><li>O design compacto do Roku Streaming Stick não bloqueia as entradas HDMI vizinhas e pode ser alimentado pela porta USB da sua TV. Ele se conecta diretamente à parte de trás da sua TV e fica super discreto. Sem tomada, sem cabos extras, sem bagunça.</li><li>Chega de usar vários controles remotos: ligue a TV, ajuste o volume e controle o dispositivo Roku com um controle remoto. Use a voz para pesquisar rápido, assistir ao seu conteúdo favorito e muito mais.</li><li>Leve sua TV favorita com você: com o design portátil desse dispositivo de streaming, você pode levar sua TV na mala quando estiver viajando, sem precisar fazer login no dispositivo de outra pessoa.</li><li>Todos os principais apps: você não vai mais precisar perguntar “Onde está passando?\". Agora todos os principais apps estão em um só lugar, para que você possa sempre fazer streaming dos seus programas de TV, filmes favoritos e muito mais.</li><li>Fácil de usar: comece imediatamente com uma tela inicial que dá acesso ao que você quer assistir de forma rápida.</li><li>TV ao vivo gratuita de verdade: aproveite dezenas de canais com notícias ao vivo, esportes, dramas e muito mais - tudo isso totalmente de graça.</li><li>Configuração rápida e fácil: basta ligar seu dispositivo, conectar-se à internet e mergulhar em um mundo de streaming.</li></ul>",
    "informacoes_produto": {
      "Marca": "Roku",
      "Tecnologia de conectividade": "Wi-fi",
      "Tipo de conector": "HDMI",
      "Características especiais": "Compatível com Apple AirPlay e HomeKit, Compatível com Google Home, Compatível com Alexa",
      "Resolução": "1080p"
    },
    "affiliate_url": "https://www.amazon.com.br/PHILIPS-Microfone-TAUE101BK-00-intra-auricular/dp/B084S6BCJN/ref=zg_bs_g_electronics_d_sccl_9/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-9",
    "title": "Smartwatch Samsung Galaxy Fit3 Display 1.6\" Grafite",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51bjAlTBzZL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 221.11,
    "price_original": 599.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 11970,
    "coupon_code": null,
    "description": "<ul><li>Para começar a usar o Galaxy Fit3, uma conta Samsung deve estar cadastrada em seu celular. Seus dados de saúde no seu Galaxy Fit3 serão transferidos com segurança e armazenados na Samsung Cloud conectada à sua conta, para que você possa acessar e gerenciar totalmente seus dados.</li><li>Quando a bateria estiver completamente descarregada, o Fit não ligará. Carregue totalmente o bateria antes de ligar o Fit.</li><li>A tela sensível ao toque pode funcionar mal em condições úmidas ou quando exposta à água.</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "FreeRTOS",
      "Capacidade de armazenamento da memória": "16 MB",
      "Características especiais": "Leve",
      "Capacidade da bateria": "3000 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartwatch-Samsung-Galaxy-Display-Grafite/dp/B0CVCLGV1W/ref=zg_bs_g_electronics_d_sccl_10/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-11",
    "title": "Banqueta Plástica Dobrável, Branca, Altura 450 Mm, Vonder",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51XGo8rKE-L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Móveis",
    "price_current": 76.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 1073,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {
      "Material": "Carvão",
      "Dimensões do produto": "12P x 30L x 8A centímetros",
      "Peso do produto": "600 Gramas",
      "Vantagens do produto": "Remove impurezas e contaminantes",
      "Marca": "SOFT"
    },
    "affiliate_url": "https://www.amazon.com.br/Banqueta-Pl%C3%A1stica-Dobr%C3%A1vel-Altura-VDO2556/dp/B078HFQHKX/ref=zg_bs_g_furniture_d_sccl_12/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-16",
    "title": "Antena de TV Interna UHF HDTV AI 2025 Preto Intelbras",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41cJdNd5ZTL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 32.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 62227,
    "coupon_code": null,
    "description": "<ul><li>Auto desligamento quando as pilhas carregam 100%</li><li>Proteção que garante o carregamento seguro</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "2500",
      "Adequação do controle por rádio": "Aparelho auditivo, Controle remoto da TV, Câmera, Drone, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/intelbras-Antena-Interna-2025-Preto/dp/B0999NKXF9/ref=zg_bs_g_electronics_d_sccl_17/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-17",
    "title": "Dolce Gusto Mochaccino Em Cápsula Avelã Nescafé Caixa 170G 10 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61-U7n6-0uL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 16.73,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 202,
    "coupon_code": null,
    "description": "<ul><li>SOM JBL PURE BASS POTENTE. O fone de ouvido JBL Tune 530BT entrega graves profundos e impactantes com drivers de 33 mm, proporcionando áudio dinâmico para músicas, vídeos e chamadas ao longo do dia.</li><li>ATÉ 76 HORAS DE BATERIA. O fone de ouvido Bluetooth JBL oferece longa duração para uso contínuo, com carga rápida que garante até 5 horas de reprodução em apenas 5 minutos, ideal para rotinas intensas.</li><li>CHAMADAS CLARAS COM 2 MICROFONES. Dois microfones beamforming captam sua voz com precisão e reduzem ruídos externos, proporcionando conversas nítidas mesmo em ambientes movimentados.</li><li>CONEXÃO MULTIPONTO BLUETOOTH 6.0. Alterne facilmente entre dois dispositivos conectados. O fone de ouvido Bluetooth JBL mantém áudio estável, sincronizado e com menor consumo de energia.</li><li>CONFORTO LEVE E DESIGN DOBRÁVEL. O fone de ouvido JBL conta com almofadas macias e estrutura leve para uso prolongado. Dobrável e prático, acompanha sua rotina com conforto e facilidade de transporte.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Cor": "Preto",
      "Colocação na orelha": "Extra-auriculares",
      "Fator de forma dos fones de ouvido": "Extra-auriculares",
      "Impedância": "20 Ohms"
    },
    "affiliate_url": "https://www.amazon.com.br/Dolce-Mochaccino-C%C3%A1psula-Nescaf%C3%A9-Unidades/dp/B0CN1L7B18/ref=zg_bs_g_kitchen_d_sccl_18/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-18",
    "title": "ELG, GENIUS, Suporte Fixo Universal de Parede Para TVs de 14” a 100”, Capacidade até 100 kg, Padrão VESA de 75x75 a 800x400mm, Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41Ap3CmMlES._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 26.49,
    "price_original": 39.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 38800,
    "coupon_code": null,
    "description": "<ul><li>SUPORTE FIXO DE PAREDE: Construído com aço de alta resistência, o suporte GENIUS da ELG oferece segurança incomparável. Seu sistema de encaixe rápido e trava de segurança garantem praticidade na instalação e uso diário.</li><li>DURÁVEL E CONFIÁVEL: Com uma garantia total de 5 anos contra defeitos de fabricação ou em suas peças, o suporte GENIUS da ELG demonstra a confiança da marca em sua qualidade superior.</li><li>ACABAMENTO PREMIUM: O acabamento em pintura eletrostática não é apenas esteticamente agradável, mas também funcional. Esta tecnologia avançada proporciona maior durabilidade ao produto e resistência superior a riscos.</li><li>FÁCIL INSTALAÇÃO: Graças ao gabarito e kit de acessórios inclusos. Seja em parede de madeira ou alvenaria, você terá todas as ferramentas necessárias para uma montagem fácil e segura.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "ELG",
      "Material": "Aço carbono",
      "Cor": "PRETO"
    },
    "affiliate_url": "https://www.amazon.com.br/Suporte-Universal-Parede-Elg-GENIUS/dp/B0765P3DB8/ref=zg_bs_g_electronics_d_sccl_19/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-19",
    "title": "ELG, GENIUS, Suporte Fixo Universal de Parede Para TVs de 14” a 100”, Capacidade até 100 kg, Padrão VESA de 75x75 a 800x400mm, Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41Ap3CmMlES._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 26.49,
    "price_original": 39.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 38817,
    "coupon_code": null,
    "description": "<ul><li>SUPORTE FIXO DE PAREDE: Construído com aço de alta resistência, o suporte GENIUS da ELG oferece segurança incomparável. Seu sistema de encaixe rápido e trava de segurança garantem praticidade na instalação e uso diário.</li><li>DURÁVEL E CONFIÁVEL: Com uma garantia total de 5 anos contra defeitos de fabricação ou em suas peças, o suporte GENIUS da ELG demonstra a confiança da marca em sua qualidade superior.</li><li>ACABAMENTO PREMIUM: O acabamento em pintura eletrostática não é apenas esteticamente agradável, mas também funcional. Esta tecnologia avançada proporciona maior durabilidade ao produto e resistência superior a riscos.</li><li>FÁCIL INSTALAÇÃO: Graças ao gabarito e kit de acessórios inclusos. Seja em parede de madeira ou alvenaria, você terá todas as ferramentas necessárias para uma montagem fácil e segura.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "ELG",
      "Material": "Aço carbono",
      "Cor": "PRETO"
    },
    "affiliate_url": "https://www.amazon.com.br/Suporte-Universal-Parede-Elg-GENIUS/dp/B0765P3DB8/ref=zg_bs_g_electronics_d_sccl_20/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-20",
    "title": "Caixa de Pilha AA com 40 unidades Elgin Palito - Tubo, Zinco",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71KcB2I6GfL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 30.23,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 11363,
    "coupon_code": null,
    "description": "<ul><li>Revestimento Dura Mais: Não deixam o alimento grudar, tem maior durabilidade e é fácil de limpa.</li><li>2 em 1 (Grill e Sanduicheira) : Prepare saborosos sanduíches, hambúrgueres , carnes, peixe, vegetais e muito mais.</li><li>Chapa superior Grill e chapa inferior lisa: Ideal para preparar diversas receitas.</li><li>Placa superior de aquecimento ajustável: Prepara alimentos de diversas espessuras sem amassar.</li><li>Compacta, prática e mais saudável: Não precisa usar óleo, proporcionando alimentos mais saudáveis.</li></ul>",
    "informacoes_produto": {
      "Cor": "Inox",
      "Material": "Plástico e Metal",
      "Marca": "Britânia",
      "Dimensões do produto": "22P x 26L x 8A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilha-Zinco-comum-AA-ELE000000082341/dp/B0B2YJK7KF/ref=zg_bs_g_electronics_d_sccl_21/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-21",
    "title": "Kit com 5 Potes de Vidro Gato Panda, 640 ml, Retangular, com Tampa Hermética, Azul",
    "image": "https://images-na.ssl-images-amazon.com/images/I/814oRtHfLLL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 59.9,
    "price_original": 99.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3942,
    "coupon_code": null,
    "description": "<ul><li>🔒 Potes de Vidro Hermético com Tampa 4 Travas e Silicone – Sistema de vedação hermética com anel de silicone removível que conserva alimentos por mais tempo. Ideal como pote de vidro com tampa para armazenamento seguro sem vazamentos.</li><li>🔥 Recipiente de Vidro 640ml para Micro-ondas, Forno e Freezer – Pote de vidro resistente a altas temperaturas (até 300°C), pode ir ao microondas, freezer e forno sem tampa. Perfeito para marmita de vidro e armazenamento térmico.</li><li>🌱 Pote de Vidro Livre de BPA para Armazenar Alimentos – Alternativa saudável aos potes plásticos. Não absorve odores, não mancha e mantém sabor original. Ideal para organização de cozinha e conservação de alimentos.</li><li>🍱 Kit 5 Potes de Vidro Retangular 640ml para Marmita e Meal Prep – Conjunto de recipientes de vidro herméticos para preparar marmitas, guardar arroz, feijão, massas, saladas e refeições prontas.</li><li>🧼 Organizador de Alimentos em Vidro Transparente Fácil de Limpar – Design empilhável, vidro durável e tampa desmontável que facilita higienização. Excelente para organização de geladeira, armário e despensa.</li></ul>",
    "informacoes_produto": {
      "Marca": "GATO PANDA",
      "Cor": "Azul",
      "Material": "Vidro borossilicato",
      "Característica do material": "Seguro para forno, Seguro para micro-ondas, Sem BPA",
      "Capacidade": "640 ml"
    },
    "affiliate_url": "https://www.amazon.com.br/Potes-Vidro-Retangular-Tampa-Herm%C3%A9tica/dp/B08CPW5BR2/ref=zg_bs_g_kitchen_d_sccl_22/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-22",
    "title": "Chaleira Elétrica 1,8l Inox Desligamento Automatico Cor Aço 110v",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51Od47eZPcL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 34.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 4348,
    "coupon_code": null,
    "description": "<ul><li>DIFERENCIAIS: A Panela de Pressão Brinox Ceramic Life Pressure com indução foi desenvolvida para agilizar o preparo das refeições do dia a dia. Com capacidade de 4,2 litros, oferece eficiência no cozimento, praticidade no uso e desempenho confiável para diferentes receitas.</li><li>MATERIAIS: O corpo da panela é produzido em alumínio, material que favorece a condução do calor e contribui para uma cocção mais rápida e uniforme. Os cabos e alças são fabricados em baquelite antitérmico, garantindo segurança no manuseio.</li><li>COMPOSIÇÃO: Possui revestimento interno antiaderente Ceramic Life, com classificação A (ótima) de antiaderência, facilitando o preparo dos alimentos e a limpeza. O sistema de pressão conta com três dispositivos de segurança: trava de segurança, válvula de trabalho e válvula de segurança.</li><li>INSTRUÇÕES DE USO E RECOMENDAÇÕES: Antes do primeiro uso, recomenda-se realizar a cura do revestimento. Após o preparo, evitar choques térmicos e efetuar a limpeza manual com esponja macia e detergente neutro, sem utilizar produtos abrasivos.</li><li>TIPOS DE FOGÕES: Compatível com fogões a gás, elétricos, vitrocerâmicos e por indução, graças ao fundo preparado para esse tipo de uso. Não deve ser utilizada em forno, micro-ondas ou lava-louças.</li><li>RESUMO: Funcional e prática, a Panela de Pressão Brinox Ceramic Life Pressure é indicada para o preparo de carnes, grãos, legumes e receitas que exigem cozimento sob pressão, oferecendo agilidade e desempenho no uso diário.</li></ul>",
    "informacoes_produto": {
      "Marca": "Brinox",
      "Capacidade": "4,2 litros",
      "Material": "Alumínio",
      "Cor": "Vanilla",
      "Tipo de acabamento": "Brilhante"
    },
    "affiliate_url": "https://www.amazon.com.br/Chaleira-El%C3%A9trica-Inox-Desligamento-Automatico/dp/B0D2S1VBQP/ref=zg_bs_g_kitchen_d_sccl_23/134-0431445-6285308?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-23",
    "title": "Dolce Gusto Mochaccino Em Cápsula Avelã Nescafé Caixa 170G 10 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61-U7n6-0uL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 16.73,
    "price_original": 0.1,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 5813,
    "coupon_code": null,
    "description": "<ul><li>MÁQUINA NESCAFÉ DOLCE GUSTO: cápsulas para o sistema Nescafé Dolce Gusto. Conheça uma das mais de 35 opções de bebidas incríveis! As máquinas e cafeteiras Nescafé Dolce Gusto podem fazer em casa suas bebidas favoritas da cafeteria: basta apertar um botão!</li><li>MOCHACCINO AVELÃ: Um verdadeiro deleite! Você só precisa de uma xícara do Mochaccino Avelã para saborear um sabor que é puro conforto! É a magia do aroma de café e o toque de sabor avelã que vai fazer você se sentir abraçado! São 10 cápsulas para aproveitar e saborear.</li><li>MODO DE PREPARO: após preencher o recipiente da sua máquina Nescafé Dolce Gusto com água, coloque uma cápsula Nescafé Dolce Gusto Mochaccino Avelã, ajuste a quantidade de água sugerida, que são 4 níveis e ligue sua máquina no modo quente.</li><li>NOSSO COMPROMISSO COM O PLANETA: 100% do nosso café é certificado por parceiros especializados. Isso quer dizer que além de sabermos de onde vem cada xícara de café. Você sabia que é fácil reciclar suas cápsulas de Nescafé Dolce Gusto? Basta colocar as cápsulas usadas em um saco ou caixa de papelão para que não suje ou molhe os outros materiais recicláveis. E caso haja muito líquido nas cápsulas, você pode deixá-las escorrendo por um tempinho antes de descartá-las. Não é preciso lavá-las e nem retirar o conteúdo interno. Descarte em um lixo reciclável e suas cápsulas serão encaminhadas para uma cooperativa e após os processos sua cápsula ganha uma segunda vida e se tornará um novo objeto!</li></ul>",
    "informacoes_produto": {
      "Marca": "Nescafé Dolce Gusto",
      "Forma do produto": "Cápsula",
      "Sabor": "Avelã",
      "Descrição do teor de cafeína": "Com cafeína",
      "Nível de torragem": "Torra clara"
    },
    "affiliate_url": "https://www.amazon.com.br/Dolce-Mochaccino-C%C3%A1psula-Nescaf%C3%A9-Unidades/dp/B0CN1L7B18/ref=zg_bs_g_kitchen_d_sccl_24/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-25",
    "title": "Pilha Panasonic Comum AA c/04 unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61sfR1a-7eL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 17.0,
    "price_original": 17.99,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5598,
    "coupon_code": null,
    "description": "<ul><li>Excelente custo/benefício</li><li>Comum</li><li>Característica do produto: pequena</li><li>Voltagem: 1, 5V Conserto/ Troca: Troca</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA (necessita de baterias)",
      "Marca": "Panasonic",
      "Composição das células da bateria": "Alcalina",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "4.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Panasonic-UM-3SHS-PILHA-COMUM-AA/dp/B075XFDPL2/ref=zg_bs_g_electronics_d_sccl_26/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-26",
    "title": "Pilha Panasonic Comum AA c/04 unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61sfR1a-7eL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 17.0,
    "price_original": 17.99,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5602,
    "coupon_code": null,
    "description": "<ul><li>Excelente custo/benefício</li><li>Comum</li><li>Característica do produto: pequena</li><li>Voltagem: 1, 5V Conserto/ Troca: Troca</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA (necessita de baterias)",
      "Marca": "Panasonic",
      "Composição das células da bateria": "Alcalina",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "4.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Panasonic-UM-3SHS-PILHA-COMUM-AA/dp/B075XFDPL2/ref=zg_bs_g_electronics_d_sccl_27/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-27",
    "title": "Mor - Tábua Retangular Bamboo 35cm x 25cm",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61sVKvVjClL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 31.35,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 17867,
    "coupon_code": null,
    "description": "<ul><li>Bamboo</li><li>Marrom</li><li>90 Dias</li></ul>",
    "informacoes_produto": {
      "Marca": "MOR",
      "Cor": "Palha",
      "Dimensões do produto": "35C x 25L x 1,5Espessura centímetros",
      "Material": "Madeira",
      "Adequação do controle por rádio": "Corte de legumes, verduras e carnes, Servir alimentos"
    },
    "affiliate_url": "https://www.amazon.com.br/T%C3%A1bua-Retangular-Bamboo-Mor-35/dp/B076X5ZLZQ/ref=zg_bs_g_kitchen_d_sccl_28/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-28",
    "title": "Caixa de Pilha AAA com 40 unidades Elgin Palito - Tubo, Zinco",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51wlcSTwZsL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 28.7,
    "price_original": 0.72,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 7417,
    "coupon_code": null,
    "description": "<ul><li>Caixa com 40 pilhas de zinco AAA Palito</li><li>Ideal para aparelhos que requerem descargas de energia rápidas e fortes.</li><li>Pilhas aprovadas pelo INMETRO: Testadas periodicamente por laboratórios credenciados pelo INMETRO, para garantir a qualidade e conformidade com a resolução Conama 401.</li><li>As pilhas Elgin têm ótima relação custo/benefício, você economiza e ainda conta com pilhas de alta qualidade.</li><li>Ecologicamente corretas: As Pilhas da Elgin têm 0% de Mercúrio e Cadmio em sua composição, colaborando para a preservação do meio ambiente.</li><li>Validade de 3 anos.</li><li>Voltagem 1.5V.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "40 AAA baterias necessárias. (inclusas)",
      "Marca": "Elgin",
      "Composição das células da bateria": "Zinco",
      "Adequação do controle por rádio": "Controle remoto da TV",
      "Contagem de unidades": "40.0 Unidade"
    },
    "affiliate_url": "https://www.amazon.com.br/Elgin-PILHA-ZINCO-COMUM-Laranja/dp/B09LD48ZZ4/ref=zg_bs_g_electronics_d_sccl_29/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-29",
    "title": "Duracell Pilhas Moeda CR2032 Pack 2 Unidades – Ideal para Placas Mãe e Controles Automotivos",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71TJ3Ud6gtL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 19.9,
    "price_original": 24.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 26590,
    "coupon_code": null,
    "description": "<ul><li>As pilhas moeda são usadas em chaveiros, controles remotos, chaves de carro, balanças, calculadoras, acessórios vestíveis (como óculos e relógios), entre outros..</li><li>As pilhas moeda são usadas em sensores, equipamentos médicos (medidores de glicemia, termômetros digitais), aparelhos desportivos (medidor de ritmo cardíaco, acessórios de ciclismo), entre outros.</li><li>A embalagem reforçada garante a segurança dos seus filhos: ela só pode ser aberta com uma tesoura.</li><li>A tecnologia de Duracell preserva a energia das pilhas que ainda não foram usadas, por até 10 anos.</li><li>As pilhas moeda Duracell 2032 são fabricadas com lítio de elevada pureza e têm energia de longa duração para diferentes equipamentos.</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "2 Íon de lítio (necessita de baterias)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "255",
      "Adequação do controle por rádio": "Controles automotivos, Placas-mãe de computador, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Duracell-Pilhas-Unidades-Controles-Automotivos/dp/B08DQQC61G/ref=zg_bs_g_electronics_d_sccl_30/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-30",
    "title": "Escadinha Infantil 2 Degraus, Clingo, Azul",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61H18Yz9FvL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Móveis",
    "price_current": 61.1,
    "price_original": 79.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1107,
    "coupon_code": null,
    "description": "<ul><li>Acesso em Alta: A Escadinha ajuda seu pequeno a alcançar a pia, vaso sanitário e banheira, tornando as tarefas diárias muito mais fáceis!</li><li>Segurança em Primeiro Lugar: Com borracha antiderrapante, sua criança fica segura durante o uso, permitindo que ela suba e desça sem preocupações!</li><li>Multiuso e Prática: Pode ser usada como um banquinho para ajudar mamães na hora do banho, oferecendo versatilidade e praticidade na rotina!</li><li>Compacta e Fácil de Guardar: Seu design inteligente permite que a escada seja armazenada facilmente, ideal para espaços pequenos!</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "27P x 37L x 17A centímetros",
      "Marca": "Clingo",
      "Material": "Polipropileno (PP)",
      "Cor": "Azul",
      "Características especiais": "Base larga para maior estabilidade e segurança., Degraus antiderrapante., Suporta até 80kg"
    },
    "affiliate_url": "https://www.amazon.com.br/Escadinha-infantil-degraus-Clingo-Azul/dp/B07GF35WDR/ref=zg_bs_g_furniture_d_sccl_31/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-31",
    "title": "BLACK+DECKER Mixer Multiuso Sem Fio com Haste Removível M150",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51voSZgLbTL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 49.78,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2138,
    "coupon_code": null,
    "description": "<ul><li>DESIGN LEVE - Um terço mais leve do que as garrafas de aço inoxidável normais, graças à tecnologia AeroLight. Torna esta garrafa de água ideal para colocar na sua bolsa de trabalho, escola, faculdade ou academia.</li><li>DURÁVEL E ISOLADA - Fabricado em aço inoxidável 18/8 com isolamento a vácuo de parede dupla para um desempenho térmico duradouro. Tanto para bebidas quentes ou frias; mantém o seu café ou chá quente durante 8 horas, a sua água ou refrigerante gelados durante 12 horas e frescos durante 40 horas.</li><li>À PROVA DE VAZAMENTOS E SEGURA – Possui uma tampa com bloqueio e abertura para beber, garantindo transporte à prova de vazamentos, e a base estreita se encaixa na maioria dos porta-copos de carro.</li><li>MANUTENÇÃO FÁCIL - Pode ser lavada na máquina de lavar louça e não contém BPA.</li><li>STANLEY - Com uma rica história de 100 anos, a marca Stanley nos trouxe o isolamento a vácuo e revolucionou a maneira como consumimos bebidas. Do quente ao frio, os produtos Stanley são icônicos, duráveis e feitos para as aventuras modernas. Prepare-se para começar a sua.</li></ul>",
    "informacoes_produto": {
      "Marca": "Stanley",
      "Capacidade": "591 ml",
      "Cor": "Black",
      "Adequação do controle por rádio": "Café",
      "Características especiais": "Leve, À prova de vazamentos"
    },
    "affiliate_url": "https://www.amazon.com.br/BLACK-DECKER-Misturador-Multiuso-M150-BR/dp/B08BG687L9/ref=zg_bs_g_kitchen_d_sccl_32/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-32",
    "title": "Duracell Pilhas Moeda CR2032 Pack 2 Unidades – Ideal para Placas Mãe e Controles Automotivos",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71TJ3Ud6gtL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 19.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5348,
    "coupon_code": null,
    "description": "<ul><li>MULTIPLICADOR DE TOMADAS: Compacto, e em formato de cubo, o PowerCube transforma uma única tomada em 5 pontos de energia, que podem ser utilizadas simultaneamente para carregamento rápido de dispositivos eletrônicos.</li><li>TRAVA PARA CRIANÇAS: O sistema Child Lock garante proteção extra ao impedir a inserção acidental de objetos nas tomadas, liberando a entrada apenas quando os pinos são inseridos simultaneamente.</li><li>DESIGN PREMIADO: Com design premiado internacionalmente, sua estrutura única permite conectar todos os plugues ao mesmo tempo, sem bloqueios entre si. É ideal para uso em residências, escritórios e hotéis.</li><li>QUALIDADE PREMIUM: Fabricado em policarbonato antichamas, com conectores em cobre de alta pureza e certificação pelo Inmetro, obtenha segurança e eficiência em um produto bivolt de alto padrão.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Marca": "ELG",
      "Cor": "Verde e Branco",
      "Total de tomadas de energia": "5",
      "Tensão": "110 Volts, 220 Volts",
      "Características especiais": "Proteção de sobretensão"
    },
    "affiliate_url": "https://www.amazon.com.br/Duracell-Pilhas-Unidades-Controles-Automotivos/dp/B08DQQC61G/ref=zg_bs_g_electronics_d_sccl_33/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-34",
    "title": "PIX Suporte de TV Fixo Universal 10 a 100 Polegadas Compacto Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/617C5sIk3sL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 9.4,
    "price_original": 12.5,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1242,
    "coupon_code": null,
    "description": "<ul><li>Suporte Fixo Universal 10 a 100 Polegadas – Compatível com a maioria das TVs, ideal para otimizar espaço em salas, quartos e ambientes comerciais.</li><li>Capacidade de até 80 kg – Estrutura reforçada para suportar TVs grandes com estabilidade e segurança.</li><li>Instalação fácil – Acompanha kit completo de buchas e parafusos, garantindo praticidade na montagem.</li><li>Compatível com padrão VESA 75x75 a 800x400 mm – Ajuste simples a diferentes modelos e tamanhos de TVs sem complicações.</li><li>Garantia de 5 anos – Confiabilidade e durabilidade asseguradas para uso residencial e profissional.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "PIX",
      "Material": "Metal",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/PIX-Suporte-Universal-Polegadas-Compacto/dp/B0CM27NSBG/ref=zg_bs_g_electronics_d_sccl_35/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-35",
    "title": "PIX Suporte de TV Fixo Universal 10 a 100 Polegadas Compacto Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/617C5sIk3sL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Eletrônicos",
    "price_current": 9.4,
    "price_original": 12.5,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 1247,
    "coupon_code": null,
    "description": "<ul><li>Suporte Fixo Universal 10 a 100 Polegadas – Compatível com a maioria das TVs, ideal para otimizar espaço em salas, quartos e ambientes comerciais.</li><li>Capacidade de até 80 kg – Estrutura reforçada para suportar TVs grandes com estabilidade e segurança.</li><li>Instalação fácil – Acompanha kit completo de buchas e parafusos, garantindo praticidade na montagem.</li><li>Compatível com padrão VESA 75x75 a 800x400 mm – Ajuste simples a diferentes modelos e tamanhos de TVs sem complicações.</li><li>Garantia de 5 anos – Confiabilidade e durabilidade asseguradas para uso residencial e profissional.</li></ul>",
    "informacoes_produto": {
      "Tipo de montagem": "Montagem na parede",
      "Tipo de movimento": "Fixado",
      "Marca": "PIX",
      "Material": "Metal",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/PIX-Suporte-Universal-Polegadas-Compacto/dp/B0CM27NSBG/ref=zg_bs_g_electronics_d_sccl_36/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-36",
    "title": "Suporte para Notebook e MacBook em Alumínio Dobrável Ergonômico Ajustável 6 Níveis com Altura Regulável Base Antiderrapante para Laptop Tablet de 10 a 17 Polegadas com Bolsa de Transporte Premium",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51n5lpVgMEL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Móveis",
    "price_current": 20.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 17730,
    "coupon_code": null,
    "description": "<ul><li>Verifique a voltagem antes de comprar o produto para certificar-se de que corresponde à da sua região</li><li>Tampa com trava de segurança</li><li>Base de contato separada</li><li>Com trava de segurança</li><li>Botão liga/desliga</li><li>Base separada</li><li>Luz LED operacional</li><li>Desliga automaticamente</li></ul>",
    "informacoes_produto": {
      "Marca": "Agratto",
      "Capacidade": "1,8 litros",
      "Material": "Aço inoxidável, Plástico",
      "Cor": "Preto/Inox",
      "Informações de embalagem": "RM"
    },
    "affiliate_url": "https://www.amazon.com.br/Ergon%C3%B4mico-Ajust%C3%A1vel-Regul%C3%A1vel-Antiderrapante-Transporte/dp/B0H3T5K8FW/ref=zg_bs_g_furniture_d_sccl_37/134-0431445-6285308?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-37",
    "title": "Tramontina JOGO FACAS INOX 4PC PLENUS PRE, Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71EvJYnDRYL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 29.9,
    "price_original": 37.61,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 12789,
    "coupon_code": null,
    "description": "<ul><li>Jogo de Facas Tramontina Plenus com Lâminas em Aço Inox e Cabos de Polipropileno Preto 04 Peças</li><li>Número de modelo: 23498064</li><li>Nome de modelo: PLENUS</li><li>Tipo de produto: HOME</li></ul>",
    "informacoes_produto": {
      "Material da lâmina": "Aço inoxidável",
      "Marca": "Tramontina",
      "Cor": "Preto",
      "Material do cabo": "Polipropileno",
      "Borda da lâmina": "Plana"
    },
    "affiliate_url": "https://www.amazon.com.br/Tramontina-JOGO-FACAS-PLENUS-Preto/dp/B09XFD2YMF/ref=zg_bs_g_kitchen_d_sccl_38/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-38",
    "title": "Rodízio Kit 5 Rodinhas Cadeira Escritório Silicone Antirisco",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41RFmwHqvzL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Móveis",
    "price_current": 29.9,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 17722,
    "coupon_code": null,
    "description": "<ul><li>Verifique a voltagem antes de comprar o produto para certificar-se de que corresponde à da sua região</li><li>Tampa com trava de segurança</li><li>Base de contato separada</li><li>Com trava de segurança</li><li>Botão liga/desliga</li><li>Base separada</li><li>Luz LED operacional</li><li>Desliga automaticamente</li></ul>",
    "informacoes_produto": {
      "Marca": "Agratto",
      "Capacidade": "1,8 litros",
      "Material": "Aço inoxidável, Plástico",
      "Cor": "Preto/Inox",
      "Informações de embalagem": "RM"
    },
    "affiliate_url": "https://www.amazon.com.br/Rod%C3%ADzio-Rodinhas-Escrit%C3%B3rio-Silicone-Antirisco/dp/B0D9PRYS4D/ref=zg_bs_g_furniture_d_sccl_39/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-39",
    "title": "Jogo de 6 Copos Sofia, Vidro Transparente, 450ml, Design Canelado Vertical, para Água, Sucos e Drinks",
    "image": "https://images-na.ssl-images-amazon.com/images/I/71+tqBymsSL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 29.9,
    "price_original": 44.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 20,
    "coupon_code": null,
    "description": "<ul><li>DESIGN CANELADO ELEGANTE: O acabamento canelado vertical confere sofisticação e um efeito visual refinado, valorizando a apresentação das bebidas.</li><li>JOGO COMPLETO COM 6 COPOS: Conjunto com 6 copos Sofia de 450ml cada, ideais para uso diário ou ocasiões especiais com estilo e praticidade.</li><li>VERSATILIDADE: Perfeitos para servir água, sucos, refrigerantes, drinks e coquetéis, combinando com diferentes estilos de mesa e ambientes.</li><li>VIDRO TRANSPARENTE DE ALTA QUALIDADE: Fabricados em vidro resistente e transparente, unindo beleza e durabilidade para o dia a dia.</li><li>ESTILO MODERNO: O design sofisticado combina perfeitamente com cozinhas modernas, mesas postas e ambientes que valorizam a elegância.</li></ul>",
    "informacoes_produto": {
      "Marca": "GATAO",
      "Material": "Vidro de borossilicato",
      "Cor": "Transparente",
      "Capacidade": "90 ml",
      "Características especiais": "Parede Dupla Isolante"
    },
    "affiliate_url": "https://www.amazon.com.br/Sofia-Transparente-Design-Canelado-Vertical/dp/B0H5TGYNPL/ref=zg_bs_g_kitchen_d_sccl_40/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-40",
    "title": "Melitta Filtro de Papel 102 - 30 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81ZrxBKCaCL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 4.49,
    "price_original": 0.15,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 648,
    "coupon_code": null,
    "description": "<ul><li>Muita tecnologia para o seu café ficar sempre fresquinho e para você sentir mais a vida. Possuem microfuros e dupla costura/ disponível nos tamanhos 100 (200ml ou 4 xícaras ou 1 caneca - ideal para o preparo individual), 102 (800ml ou 16 xícaras) e 103 (1000ml ou 20 xícaras)</li><li>Tamanho 102 (ideal para preparar 800ml ou 16 xícaras de café)</li><li>Contem 30 filtros de papel</li><li>Único com microfuros</li></ul>",
    "informacoes_produto": {
      "Material": "Papel",
      "Marca": "Melitta",
      "Forma": "Cone",
      "Número de peças": "1",
      "Dispositivos compatíveis": "Cafeteira"
    },
    "affiliate_url": "https://www.amazon.com.br/Filtro-para-Caf%C3%A9-102-Melitta/dp/B078XNNYG6/ref=zg_bs_g_kitchen_d_sccl_41/142-5460739-9241728?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-41",
    "title": "Melitta Filtro de Papel 102 - 30 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/81ZrxBKCaCL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 4.49,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 960,
    "coupon_code": null,
    "description": "<ul><li>🌍 Adaptação Total em +150 Países Viaje com liberdade total! Com suporte para os plugues dos tipos A, B, C, D, E, F, G e I, este adaptador universal é compatível com mais de 150 países — incluindo Estados Unidos, Reino Unido, Japão, Austrália e toda a União Europeia. Ideal para quem viaja a trabalho ou lazer e não quer correr riscos com conectividade.</li><li>⚡ Tecnologia Bivolt Inteligente Compatível com tensões de 110V a 220V, o adaptador ajusta automaticamente a voltagem local, protegendo seus dispositivos contra picos de energia. Sem necessidade de ajustes manuais, sem riscos de queima — conecte e relaxe.</li><li>🧳 Compacto e Portátil – Cabe em Qualquer Espaço Leve, dobrável e fácil de guardar. Ideal para malas de mão, mochilas ou estojos de eletrônicos. O design inteligente com plugues retráteis evita volume desnecessário e é perfeito para o dia a dia ou viagens longas.</li><li>🛡️ Segurança de Ponta: Proteção Total Contra Sobrecarga Equipado com sistemas de proteção contra curto-circuito, sobrecarga e superaquecimento, garantindo a segurança dos seus dispositivos e tranquilidade durante o uso, em qualquer lugar do mundo.</li><li>💎 Durabilidade Profissional com Acabamento Premium Fabricado com materiais de alta qualidade, resistente ao desgaste diário e a impactos leves. Perfeito para uso recorrente por viajantes frequentes, empresários e famílias.</li><li>💎 Pinos retrateis</li><li>💎 LED indicador de energia.</li></ul>",
    "informacoes_produto": {
      "Marca": "Genérico",
      "Cor": "branco",
      "Tensão de saída": "220 Volts",
      "Tipo de plugue": "Tipo C, Tipo E, Tipo F",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Filtro-para-Caf%C3%A9-102-Melitta/dp/B078XNNYG6/ref=zg_bs_g_kitchen_d_sccl_42/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "index-43",
    "title": "Electrolux Kit Bowls Tigelas de Inox com Tampa Plástica, 3 Unidades",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51hUmO15FhL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Cozinha",
    "price_current": 99.9,
    "price_original": 159.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 9918,
    "coupon_code": null,
    "description": "<ul><li>Conjunto formado por três bowls de aço inoxidável com tampa plástica para preparar servir e conservar alimentos na geladeira.</li><li>Com 3 tamanhos, atendem as mais variadas necessidades, como temperar carnes, fazer massas, servir saladas e preparar molhos.</li><li>Feitos de aço inoxidável, são mais duráveis e o acabamento polido facilita a limpeza. Perfeitos para preparar e servir, além de decorar a mesa.</li><li>Este produto pode ser usado no refrigerador e lavado na lava-louças.</li><li>Informações técnicas: Ø 22cm | 2,6 L Ø 19,5cm | 2 L Ø 17,5cm | 1,4 L</li></ul>",
    "informacoes_produto": {
      "Material da tigela": "Aço inoxidável",
      "Número de peças": "3",
      "Marca": "Electrolux",
      "Cor": "Inox",
      "Características especiais": "Durável, Seguro para congelador"
    },
    "affiliate_url": "https://www.amazon.com.br/Conjunto-Bowls-Tigelas-Pl%C3%A1stica-Electrolux/dp/B0C2ZNDWK6/ref=zg_bs_g_kitchen_d_sccl_44/141-1363282-2948149?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B09GSQMVJS",
    "title": "L'Oréal Professionnel Inforcer Shampoo Fortificante Antiqueda por Quebra, Crescimento Saudável Para Cabelos Frágeis e Quebradiços Com Biotina e Vitamina B6, 300ml",
    "image": "https://m.media-amazon.com/images/I/51TvgvfNA9L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 67.4,
    "price_original": 116.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7277,
    "coupon_code": null,
    "description": "<ul><li>Um tratamento em shampoo que limpa, fortalece e proporciona uma ação anti-quebra instantânea nos fios.</li><li>Enriquecido com Biotina e Vitamina B6, que estimulam o crescimento saudável e o metabolismo de proteínas.</li><li>Leva nutrientes à fibra capilar, promovendo força instantânea e prevenindo o ressecamento e a quebra.</li><li>Com o uso contínuo, os cabelos se tornam mais resistentes, com menos queda e com um crescimento visível.</li><li>Conquiste cabelos suplementados com força, nutridos, resistentes e com o crescimento saudável que você deseja.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Líquido",
      "Tipo de cabelo": "Todos os tipos de cabelos",
      "Aroma": "Sem perfume",
      "Faixa etária (descrição)": "Adulto"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Fortificante-Anti-Quebra-Quebradi%C3%A7os/dp/B09GSQMVJS?ref=dlx_deals_dg_dcl_B09GSQMVJS_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0C5DXJ165",
    "title": "Placa de Video Gigabyte RX 7600 Gaming OC, 8gb, GDDR6 - GV-R76GAMING-OC-8GD",
    "image": "https://m.media-amazon.com/images/I/71U03CcRZzL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 1699.99,
    "price_original": 1952.93,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 456,
    "coupon_code": null,
    "description": "<ul><li>GPU GIGABYTE AMD RADEON</li><li>RX 7600 GAMING</li><li>8GB 128BITS GDDR6</li><li>GIGABYTE</li></ul>",
    "informacoes_produto": {
      "Coprocessador gráfico": "AMD Radeon RX 7600",
      "Marca": "GIGABYTE",
      "Tamanho da memória RAM da placa gráfica": "8.0",
      "Velocidade do clock da GPU": "2805 MHz",
      "Interface de saída de vídeo": "DisplayPort"
    },
    "affiliate_url": "https://www.amazon.com.br/Placa-Video-Gigabyte-Gaming-GDDR6/dp/B0C5DXJ165?ref=dlx_deals_dg_dcl_B0C5DXJ165_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B61WJRY5",
    "title": "Samsung Lava e Seca WD11M com Digital Inverter WD11M4473PX Inox Look 11/7kg - 220V",
    "image": "https://m.media-amazon.com/images/I/41F+xukODBL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 3599.0,
    "price_original": 4913.82,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 511,
    "coupon_code": null,
    "description": "<ul><li>Inverter</li><li>Cuidado com lã</li></ul>",
    "informacoes_produto": {
      "Capacidade": "11 quilogramas",
      "Cor": "Inox Look",
      "Marca": "Samsung",
      "Dimensões do produto": "65P x 60L x 85A centímetros",
      "Características especiais": "Cuidado com lã, Inverter"
    },
    "affiliate_url": "https://www.amazon.com.br/Lava-Seca-Samsung-Programas-Lavagem/dp/B0B61WJRY5?ref=dlx_deals_dg_dcl_B0B61WJRY5_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": true
  },
  {
    "asin": "B0CVZ661SW",
    "title": "Ar Condicionado Split Piso Teto Inverter Elgin Plus 56000 BTU/h Frio Monofásico 45PDFI60C2DA – 220 Volts",
    "image": "https://m.media-amazon.com/images/I/51e7366ufRL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 8599.0,
    "price_original": 10499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 2,
    "coupon_code": null,
    "description": "<ul><li>Tecnologia Inverter: economia de energia e temperatura mais estável</li><li>Classificação A em eficiência: baixo consumo e economia na conta</li><li>Gás ecológico R-32: alta eficiência e menor impacto ambiental</li><li>Duplo swing na unidade interna: melhor distribuição do ar no ambiente</li><li>Serpentina de cobre + proteção azul: alta durabilidade e resistência</li></ul>",
    "informacoes_produto": {
      "Marca": "Elgin",
      "Capacidade": "196,6 quilogramas",
      "Energia de resfriamento": "56000 BTUs",
      "Características especiais": "Inverter",
      "Dimensões do produto": "23P x 60L x 69A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Condicionado-Inverter-Elgin-Monof%C3%A1sico-45PDFI60C2DA/dp/B0CVZ661SW?ref=dlx_deals_dg_dcl_B0CVZ661SW_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": true
  },
  {
    "asin": "B0H4J13B2M",
    "title": "Notebook Gamer Lenovo Loq, I5-12450hx, 16gb Ddr5, 1tb Ssd, Rtx 4050 6gb, 15.6\" Fhd, W11, Cinza - 83me0001br",
    "image": "https://m.media-amazon.com/images/I/51lylzSiLML._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 6099.99,
    "price_original": 6665.56,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Notebook Gamer Lenovo LOQ Intel i5 16GB RAM 1TB SSD RTX 4050</li><li>Placa de vídeo dedicada RTX 4050 6GB</li><li>Processador Intel Core i5-12450HX</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "1 TB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Windows 11",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "31 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Gamer-Lenovo-I5-12450hx-Cinza/dp/B0H4J13B2M?ref=dlx_deals_dg_dcl_B0H4J13B2M_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": true
  },
  {
    "asin": "B07FPW95CM",
    "title": "Jameson - Whiskey Irlandês, 750 ml",
    "image": "https://m.media-amazon.com/images/I/51syfbaTceL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 69.08,
    "price_original": 130.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7094,
    "coupon_code": null,
    "description": "<ul><li>Sabor suave e equilibrado com toque adocicado</li><li>Destilado triplo de alta qualidade</li><li>Ideal para drinks ou puro</li><li>Garrafa elegante e tradicional</li><li>Whiskey irlandês reconhecido mundialmente</li></ul>",
    "informacoes_produto": {
      "Marca": "Jameson",
      "Tipo de álcool": "Blended whiskey",
      "Sabor": "Whisky",
      "Número de itens": "1",
      "Teor alcoólico": "15 %"
    },
    "affiliate_url": "https://www.amazon.com.br/Jameson-Whisky-750ml/dp/B07FPW95CM?ref=dlx_deals_dg_dcl_B07FPW95CM_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FPRK5P9H",
    "title": "SEMP, Smart TV 4K UHD, 55“, Google TV, Google Assistente, Comando por Voz, Googlecast Integrado, Design Sem Bordas, Dolby Audio, 55S62",
    "image": "https://m.media-amazon.com/images/I/61mUtpPKNVL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 2099.99,
    "price_original": 2499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 166,
    "coupon_code": null,
    "description": "<ul><li>Smart TV com Google TV, Wi-Fi Dual Band, Bluetooth, Google Assistente, Dolby Audio, HDMI 2.1, HDR10+ e Googlecast Integrado</li><li>Tela 4K UHD de 55 polegadas com design sem bordas na cor preta, proporcionando imagem de alta resolução e visual moderno</li><li>Controle por comando de voz via Google Assistente para navegação prática entre aplicativos, conteúdos e configurações da TV</li></ul>",
    "informacoes_produto": {
      "Tamanho da tela": "55",
      "Marca": "Semp",
      "Tecnologia do visor": "4K UHD, LCD, OLED, UHD",
      "Resolução": "4K",
      "Taxa de atualização": "60 Hz",
      "Características especiais": "Google Assistente, Dolby Audio, HDMI 2.1, HDR10+, Googlecast Integrado, design sem bordas",
      "Componentes incluídos": "01 Televisor 55\", 01 Controle Remoto, 1 Cabo Adaptador P2/RCA",
      "Tecnologia de conectividade": "HDMI, USB, Wi-fi",
      "Proporção de tela": "16:9",
      "Dimensões do produto": "71,1P x 122,6L x 7,3A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SEMP-SMART-55S62-UHD-GOOGLE/dp/B0FPRK5P9H?ref=dlx_deals_dg_dcl_B0FPRK5P9H_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GND7R7Z8",
    "title": "Ar Condicionado Split Hi Wall LG Dual Voice AI Inverter 24.000 Btus Frio 220v R-32",
    "image": "https://m.media-amazon.com/images/I/51XtHBetEOL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 3899.0,
    "price_original": 4299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 3,
    "coupon_code": null,
    "description": "<ul><li>Comando de Voz AI</li><li>Wi-Fi ThinQ Integrado</li><li>Economia Energia 70%</li><li>Refrigeração Rápida 40%</li><li>Dual Inverter AI</li></ul>",
    "informacoes_produto": {
      "Marca": "LG",
      "Capacidade": "43 quilogramas",
      "Energia de resfriamento": "24000 BTUs",
      "Características especiais": "Controlado Remotamente, Activado por WiFi",
      "Dimensões do produto": "0,7P x 2L x 1A Metros"
    },
    "affiliate_url": "https://www.amazon.com.br/Condicionado-Split-LG-Inverter-24-000/dp/B0GND7R7Z8?ref=dlx_deals_dg_dcl_B0GND7R7Z8_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GHP4NL1J",
    "title": "Kit Rapunzel (Shampoo + Tônico + Milk Spray) - Lola From Rio",
    "image": "https://m.media-amazon.com/images/I/41OcWO275YL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 58.52,
    "price_original": 119.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 427,
    "coupon_code": null,
    "description": "<ul><li>Estimula o crescimento capilar, reduz a queda dos fios e nutre o couro cabeludo com fórmula vegana, cruelty-free e livre de sulfatos e silicones.</li><li>Kit composto por Shampoo, Tônico e Milk Spray com embalagens multicoloridas, da linha Rapunzel da marca Lola From Rio.</li><li>Fórmula leve e não oleosa indicada para uso diário, sem pesar os fios, mantendo a hidratação e o equilíbrio natural do couro cabeludo.</li></ul>",
    "informacoes_produto": {
      "Tipo de material livre": "Livre de sulfato",
      "Forma do produto": "Líquido",
      "Marca": "Lola",
      "Tipo de cabelo": "Cacheado, Danificado, Normal, Opaco, Todos"
    },
    "affiliate_url": "https://www.amazon.com.br/Rapunzel-Shampoo-T%C3%B4nico-Milk-Spray/dp/B0GHP4NL1J?ref=dlx_deals_dg_dcl_B0GHP4NL1J_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B0C9R8RC1P",
    "title": "Duracell Pilhas Alcalinas AAA Palito Pack 24 Unidades – Dura Mais - Ideal para Controle de Videogame e Brinquedos",
    "image": "https://m.media-amazon.com/images/I/81clRPwJt3L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 99.65,
    "price_original": 124.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 2463,
    "coupon_code": null,
    "description": "<ul><li>Pilha Duracell Alcalina AAA que fornece mais duração e potência para os aparelhos</li><li>Dura mais, muito mais</li><li>Longa duração: As pilhas alcalinas AA Duracell duram mais que as pilhas comuns de zinco-carbono, oferecendo energia confiável e de alto desempenho</li><li>As pilhas Duracell podem manter sua capacidade energética por até 10 anos, mesmo sem uso, garantindo energia disponível quando você precisar</li><li>Projetadas para oferecer o melhor desempenho em dispositivos de uso diário, como brinquedos, lanternas, controles remotos e teclados</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "24 AAA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "100",
      "Adequação do controle por rádio": "Brinquedos, Controle de videogame, Controle remoto"
    },
    "affiliate_url": "https://www.amazon.com.br/Pilha-AAA-Pequena-24-Unidades/dp/B0C9R8RC1P?ref=dlx_deals_dg_dcl_B0C9R8RC1P_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  },
  {
    "asin": "B08WLM2682",
    "title": "Mustela Hydra Bebê 300ml - Hidratante Infantil Corpo e Rosto - Feito com 97% de Ingredientes de Origem Natural e Hipoalergênico - Seguro Desde o Nascimento",
    "image": "https://m.media-amazon.com/images/I/510tnSLrxAL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Ofertas do dia",
    "price_current": 77.22,
    "price_original": 119.99,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 17895,
    "coupon_code": null,
    "description": "<ul><li>Loção hidratante com textura cremosa leve, deixa a pele mais macia e suave.</li><li>Seguro para uso desde o nascimento. Embalagem pump tamanho 300 ml.</li><li>Dermatologicamente Testado e Recomendado.</li><li>Com cheirinho delicado de Mustela Bebê.</li><li>Nosso principal ingrediente, feito de abacate, vem de cadeias de abastecimento orgânicas e responsáveis. Fortalece a barreira cutânea e protege o capital celular da pele.</li></ul>",
    "informacoes_produto": {
      "Marca": "Mustela",
      "Forma do produto": "Creme",
      "Peso do produto": "10,6 Onças",
      "Faixa etária (descrição)": "Criança"
    },
    "affiliate_url": "https://www.amazon.com.br/Org%C3%A2nico-Mustela-Hidratante-Corporal-Ingredientes/dp/B08WLM2682?ref=dlx_deals_dg_dcl_B08WLM2682_dt_sl14_88_pi&pf_rd_r=QFE83CZ08ZH1XQFV0046&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T14:50:49.000Z",
    "spotlight": false
  }
];
