const PRODUCTS = [
  {
    "asin": "index-12",
    "title": "Frigobar Brastemp Retrô 76 Litros Classic Black - BRA08ME (110, Volts)",
    "image": "https://images-na.ssl-images-amazon.com/images/I/51aB+FU2oFL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 1784.0,
    "price_original": 2129.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 5,
    "coupon_code": null,
    "description": "<ul><li>O Frigobar Brastemp Retrô 76L economiza até 21% de energia¹. Design vintage com pés palito, 8 cores exclusivas e o icônico logo anos 50.</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "55P x 48L x 82A centímetros",
      "Marca": "Brastemp",
      "Capacidade": "76 litros",
      "Cor": "preto",
      "Número de portas": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Brastemp-Retr%C3%B4-Litros-Classic/dp/B0GR18BSVR/ref=zg_bs_g_16745429011_d_sccl_13/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-17",
    "title": "Frigobar, 45L, Branco, 110V, Midea",
    "image": "https://images-na.ssl-images-amazon.com/images/I/31ZcsTeNcuL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 719.0,
    "price_original": 869.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 4236,
    "coupon_code": null,
    "description": "<ul><li>[Compartimento Gela Rápido] Espaço que acelera o resfriamento de seus alimentos e bebidas</li><li>[Compartimentos Adequados] Supercompacto com espaço otimizado, com espaço para garrafa 2L</li><li>[Considerar Design] 45L de capacidade, dimensões de 45,0 x 47,2 x 49,2 cm. É perfeito para dormitórios universitários, escritórios, garagens e pequenos apartamentos</li><li>[Termostato Ajustável] O controle da temperatura pode ser ajustado para melhor atender as condições de conservação dos alimentos, conforme o grau de utilização do aparelho</li><li>[Economia de Energia] Selo Procel e classificação “A” no Programa Brasileiro de Etiquetagem(PBE), mais economia para o seu bolso</li><li>[Componentes Incluídos] Frigobar e manual do usuário e garantia de 1 ano</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "52P x 52L x 46,5A centímetros",
      "Marca": "Midea",
      "Capacidade": "45 litros",
      "Configuração": "Frigobar, Termostato",
      "Cor": "Branco"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Midea-127V-MRC06B1-Branco/dp/B0778TZGBJ/ref=zg_bs_g_16745429011_d_sccl_18/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-22",
    "title": "Frigobar Eos Ice Compact 124l Efb131p Preto 110v",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41ayr0A4gwL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 1103.94,
    "price_original": 2079.09,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 99,
    "coupon_code": null,
    "description": "<ul><li>Mais espaço 124 litros</li><li>Eco-Friendly</li><li>Termostato</li><li>Compartimento Gela Rápido</li><li>Degelo Manual</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "56P x 49,5L x 84A centímetros",
      "Marca": "EOS",
      "Capacidade": "124 litros",
      "Configuração": "Compacto",
      "Cor": "Preto"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Compact-124l-Efb131p-Preto/dp/B0C9VQ3R6V/ref=zg_bs_g_16745429011_d_sccl_23/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": true
  },
  {
    "asin": "index-24",
    "title": "Smartphone Motorola Moto g15-256GB 12GB (4GB RAM+8GB Ram Boost) e Camera 50MP com AI e Night Vision Bateria de 5200 mAh Tela FHD+ 6.7\" com Superbrilho NFC - Grafite",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61kE-oxS5QL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Smartphones",
    "price_current": 949.0,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>IDEAL PARA CAMINHÃO 12V/24V – Funciona direto na bateria ou tomada (110V/220V), perfeita para viagens longas, motorhome e uso diário na estrada</li><li>GELA E CONGELA DE VERDADE (-20°C) – Não é cooler: refrigeração real que mantém bebidas geladas e conserva carnes e congelados com eficiência</li><li>BAIXO CONSUMO COM PROTEÇÃO DE BATERIA – Modos ECO e MAX + sistema inteligente que evita descarregar a bateria do veículo</li><li>CONTROLE PELO CELULAR (BLUETOOTH) – Ajuste temperatura e funções pelo app, com painel digital e memória automática</li><li>GRANDE CAPACIDADE 55L + 2 COMPARTIMENTOS – Espaço interno otimizado com cesto removível, luz LED e organização prática para alimentos e bebidas</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "71P x 40L x 50A centímetros",
      "Marca": "Maxfreeze",
      "Capacidade": "55 litros",
      "Configuração": "Portable",
      "Cor": "preto"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartphone-Motorola-g15-256GB-Bateria-Superbrilho/dp/B0DQQCGG3Q/ref=zg_bs_g_16243890011_d_sccl_25/134-8475195-8547430?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-49",
    "title": "Frigobar 45 Litros Inverter Bivolt Preto com cor Prata",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61n52lD2MJL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Frigobares",
    "price_current": 749.0,
    "price_original": 854.05,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Tecnologia Inverter - Resfriamento rápido, garante a estabilidade da temperatura, preservando os alimentos por mais tempo, contribui para uma maior economia de energia com baixo nível de ruído.</li><li>Flexi Volt - Funciona tanto em 127V quanto em 220V, garantindo segurança e liberdade para usar em qualquer tomada.</li><li>Design Compacto - No tamanho ideal para qualquer ambiente, é espaçoso e funcional. Seus 45L acomodam facilmente bebidas, alimentos e até garrafas de 2 litros.</li><li>Compartimento Extra frio - Bebidas geladas mais rápido, com praticidade e conveniência, sempre que você precisar.</li><li>Compartimento de Latas - Mais organização e otimização do espaço interno com o compartimento para latas.</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "45,5P x 47,2L x 49,2A centímetros",
      "Marca": "Midea",
      "Capacidade": "45 litros",
      "Cor": "Prata",
      "Número de portas": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Frigobar-Litros-Inverter-Bivolt-Preto/dp/B0GJFGN88Z/ref=zg_bs_g_16745429011_d_sccl_50/147-0222178-8072733?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-11",
    "title": "Smartphone Xiaomi Redmi Note 15 Preto 8GB RAM 256GB ROM (2510DRA23L) | 2510DRA23L",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61XgofTTv1L._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Celulares e Smartphones",
    "price_current": 1260.0,
    "price_original": 1499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 344,
    "coupon_code": null,
    "description": "<ul><li>Redmi Note 15 4G</li></ul>",
    "informacoes_produto": {
      "Marca": "XIAOMI",
      "Sistema operacional": "hyperos",
      "Tamanho instalado da memória RAM": "8 GB",
      "Modelo da CPU": "MediaTek Helio",
      "Capacidade de armazenamento da memória": "8 GB"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartphone-Xiaomi-Redmi-Preto-2510DRA23L/dp/B0GL9QPQYL/ref=zg_bs_g_16243890011_d_sccl_12/134-8475195-8547430?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-15",
    "title": "Smartphone Motorola Moto g86 5G - 256GB 24GB (8GB RAM+16GB Ram Boost) Tela 1.5K pOLED, 50MP Sony camera OIS Moto AI, videos em 4K, IP68 + IP69 - Grafite",
    "image": "https://images-na.ssl-images-amazon.com/images/I/514xNqIfRZL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Celulares e Smartphones",
    "price_current": 1730.0,
    "price_original": 2499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 1420,
    "coupon_code": null,
    "description": "<ul><li>A melhor tela da categoria pOLED com 1.5K de resolução e maior brilho²⁵. Veja imagens mais vivas e vibrantes em uma tela com 4500 nits de brilho.</li><li>A única Câmera Sony LYTIA com moto ai da categoria¹² . Registre a vida nos mínimos detalhes, em qualquer iluminação, usando a câmera Sony - LYTIA 600 de 50 MP.</li><li>Ultrarresistência incomparável²⁶ IP68 | IP69 e MIL STD 810H. Feito para durar, com acabamento premium, tela Corning Gorilla Glass 7i e resistência contra água, quedas e temperaturas extremas⁶,⁷.</li><li>Circule para pesquisar²⁷: agora no moto g . Circule ou toque em qualquer imagem, vídeo ou texto para pesquisar com o Google.</li><li>Bateria para o dia todo em 30 minutos¹. Aproveite a liberdade de uma bateria duradoura com carregamento ultrarrápido.</li></ul>",
    "informacoes_produto": {
      "Marca": "Motorola",
      "Sistema operacional": "Android 15",
      "Tamanho instalado da memória RAM": "8 GB",
      "Modelo da CPU": "MediaTek Helio",
      "Velocidade da CPU": "2 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartphone-Motorola-Moto-g86-5G/dp/B0FCYP5FB2/ref=zg_bs_g_16243890011_d_sccl_16/134-8475195-8547430?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": true
  },
  {
    "asin": "index-19",
    "title": "Celular Samsung Galaxy A07 128GB, 4GB, Câm. 50MP, Tela 6.7\"- Preto",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61AYtRHD0SL._AC_UL600_SR600,400_.jpg",
    "canonical": null,
    "category": "Celulares e Smartphones",
    "price_current": 791.38,
    "price_original": null,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 776,
    "coupon_code": null,
    "description": "<ul><li>- 4GB de RAM + 4GB de RAM Plus e 128GB de armazenamento interno</li><li>- O melhor processador da categoria (octa-core de 6nm)</li><li>- Câmera dupla de até 50MP</li><li>- Único com até 6 atualizações de Android e até 6 anos de atualizações de segurança</li><li>- Resistência à água e poeira IP54</li></ul>",
    "informacoes_produto": {
      "Marca": "Samsung",
      "Sistema operacional": "Android 15.0",
      "Tamanho instalado da memória RAM": "4 GB",
      "Capacidade de armazenamento da memória": "128 GB",
      "Tamanho da tela": "6,7 Polegadas"
    },
    "affiliate_url": "https://www.amazon.com.br/Celular-Samsung-Galaxy-128GB-Preto/dp/B0FPHYC9FQ/ref=zg_bs_g_16243890011_d_sccl_20/134-8475195-8547430?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-36",
    "title": "Smartphone Xiaomi Poco C71 Preto 4G 4GB RAM 128GB ROM",
    "image": "https://images-na.ssl-images-amazon.com/images/I/41GTZonlU+L._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Celulares e Smartphones",
    "price_current": 795.0,
    "price_original": 899.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 79,
    "coupon_code": null,
    "description": "<ul><li>Tela touchscreen de 6,88 pol., câmera de 32 MP, 128 GB de armazenamento expansível, Wi-Fi e GPS integrados</li><li>Design fino de apenas 8,3 mm de espessura, cor preta, com resolução de tela de 1640x720 pixels e 4 GB de RAM</li><li>Grava vídeos em Full HD (1920x1080 px), conexão USB tipo C e rede UMTS para transferência de dados e navegação web</li></ul>",
    "informacoes_produto": {
      "Marca": "XIAOMI",
      "Sistema operacional": "hyperOS",
      "Tamanho instalado da memória RAM": "4 GB",
      "Modelo da CPU": "Cortex",
      "Capacidade de armazenamento da memória": "4 GB"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartphone-Xiaomi-Poco-Preto-128GB/dp/B0FZDY3W26/ref=zg_bs_g_16243890011_d_sccl_37/134-8475195-8547430?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "index-45",
    "title": "Smartphone Xiaomi Redmi Note 14 Midnight Black (Preto) 8GB RAM 256GB ROM",
    "image": "https://images-na.ssl-images-amazon.com/images/I/61+k2EbgHLL._AC_UL300_SR300,200_.jpg",
    "canonical": null,
    "category": "Celulares e Smartphones",
    "price_current": 1385.0,
    "price_original": 1999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5593,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {
      "Marca": "XIAOMI",
      "Sistema operacional": "Android",
      "Tamanho instalado da memória RAM": "8 GB",
      "Modelo da CPU": "MediaTek Helio P60T",
      "Velocidade da CPU": "2,2 GHz"
    },
    "affiliate_url": "https://www.amazon.com.br/Smartphone-Xiaomi-Redmi-Midnight-Black/dp/B0DT5LHPMX/ref=zg_bs_g_16243890011_d_sccl_46/134-8475195-8547430?psc=1&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": true
  },
  {
    "asin": "B0B61WJRY5",
    "title": "Samsung Lava e Seca WD11M com Digital Inverter WD11M4473PX Inox Look 11/7kg - 220V",
    "image": "https://m.media-amazon.com/images/I/41F+xukODBL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Máquinas Lava e Seca",
    "price_current": 3599.0,
    "price_original": 0.84,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 508,
    "coupon_code": null,
    "description": "<ul><li>Inverter</li><li>Cuidado com lã</li></ul>",
    "informacoes_produto": {
      "Capacidade": "11 quilogramas",
      "Cor": "Inox Look",
      "Marca": "Samsung",
      "Dimensões do produto": "65P x 60L x 85A centímetros",
      "Características especiais": "Cuidado com lã, Inverter"
    },
    "affiliate_url": "https://www.amazon.com.br/Lava-Seca-Samsung-Programas-Lavagem/dp/B0B61WJRY5?ref=dlx_deals_dg_dcl_B0B61WJRY5_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H4HYLQ71",
    "title": "Notebook Gamer Lenovo Loq 15irx9, 15.6\" Full Hd 144hz, Intel Core I5-13450hx, 16gb, 512gb Ssd, Nvidia Rtx 4050, Linux - 83khs00300",
    "image": "https://m.media-amazon.com/images/I/61+CippnCvL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Laptops Tradicionais",
    "price_current": 5899.0,
    "price_original": 6555.54,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 5,
    "coupon_code": null,
    "description": "<ul><li>Processador estável Intel Core i5-13450HX</li><li>Tela Gamer com taxa de 144Hz</li><li>Notebook Gamer Lenovo LOQ 15IRX9 i5 16GB 512GB SSD RTX 4050 144Hz</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ 15IRX9",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "512 GB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Linux",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "49 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-15irx9-I5-13450hx-Nvidia/dp/B0H4HYLQ71?ref=dlx_deals_dg_dcl_B0H4HYLQ71_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": true
  },
  {
    "asin": "B0H4J13B2M",
    "title": "Notebook Gamer Lenovo Loq, I5-12450hx, 16gb Ddr5, 1tb Ssd, Rtx 4050 6gb, 15.6\" Fhd, W11, Cinza - 83me0001br",
    "image": "https://m.media-amazon.com/images/I/51lylzSiLML._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Laptops Tradicionais",
    "price_current": 6099.99,
    "price_original": 6665.56,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 1,
    "coupon_code": null,
    "description": "<ul><li>Notebook Gamer Lenovo LOQ Intel i5 16GB RAM 1TB SSD RTX 4050</li><li>Placa de vídeo dedicada RTX 4050 6GB</li><li>Processador Intel Core i5-12450HX</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "LOQ",
      "Tamanho da tela": "15,6 Polegadas",
      "Tamanho do disco rígido": "1 TB",
      "Modelo da CPU": "Intel Core i5",
      "Tamanho instalado da memória RAM": "16 GB",
      "Sistema operacional": "Windows 11",
      "Descrição da placa de vídeo": "Dedicada",
      "Velocidade da CPU": "31 GHz",
      "Descrição do disco rígido": "SSD"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Gamer-Lenovo-I5-12450hx-Cinza/dp/B0H4J13B2M?ref=dlx_deals_dg_dcl_B0H4J13B2M_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B07VRYJWPB",
    "title": "Finish Power Powder Advanced Detergente para Lava Louças em Pó 2,5kg",
    "image": "https://m.media-amazon.com/images/I/61FuIlOh2GL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Produtos de Limpeza para Cozinha",
    "price_current": 98.78,
    "price_original": 146.59,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 22479,
    "coupon_code": null,
    "description": "<ul><li>Finish Power Powder Advanced é o seu detergente lava louças em pó que oferece limpeza profunda na dose certa. Recomendado pelos principais fabricantes de lava louças do Brasil e do mundo.</li><li>Sua louça do dia a dia vai ficar limpa de primeira, sem necessidade de pré-enxague. Possui ingredientes na fórmula que promovem o cuidado e proteção das louças.</li><li>Exclusiva fórmula com oxigênio ativo e enzimas que promovem limpeza através de sua ação desengordurante e da remoção de sujeiras.</li><li>Vem com medidor que ajuda a dosar corretamente a quantidade do detergente lava louças.</li><li>Usar lava louças remove até as sujeiras mais difíceis, sem bagunça, sem ressecar as mãos. É mais qualidade de vida!</li></ul>",
    "informacoes_produto": {
      "Marca": "Finish",
      "Forma do produto": "Pó",
      "Aroma": "Sem perfume",
      "Característica do material": "Sem perfume",
      "Número de itens": "4"
    },
    "affiliate_url": "https://www.amazon.com.br/Detergente-Para-Lou%C3%A7as-Finish-Advanced/dp/B07VRYJWPB?ref=dlx_deals_dg_dcl_B07VRYJWPB_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0C5DXJ165",
    "title": "Placa de Video Gigabyte RX 7600 Gaming OC, 8gb, GDDR6 - GV-R76GAMING-OC-8GD",
    "image": "https://m.media-amazon.com/images/I/71U03CcRZzL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Placas de Vídeo",
    "price_current": 1699.99,
    "price_original": 1952.93,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 452,
    "coupon_code": null,
    "description": "<ul><li>GPU GIGABYTE AMD RADEON</li><li>RX 7600 GAMING</li><li>8GB 128BITS GDDR6</li><li>GIGABYTE</li></ul>",
    "informacoes_produto": {
      "Coprocessador gráfico": "AMD Radeon RX 7600",
      "Marca": "GIGABYTE",
      "Tamanho da memória RAM da placa gráfica": "8.0",
      "Velocidade do clock da GPU": "2805 MHz",
      "Interface de saída de vídeo": "DisplayPort"
    },
    "affiliate_url": "https://www.amazon.com.br/Placa-Video-Gigabyte-Gaming-GDDR6/dp/B0C5DXJ165?ref=dlx_deals_dg_dcl_B0C5DXJ165_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0GM1LSHQF",
    "title": "JBL, Fone de Ouvido Bluetooth Over-Ear, Tune 530BT, Sem Fio, Até 76 Horas de Bateria - Preto",
    "image": "https://m.media-amazon.com/images/I/61q9MOnS+2L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Fones de Ouvido Abertos",
    "price_current": 199.0,
    "price_original": 299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 202,
    "coupon_code": null,
    "description": "<ul><li>SOM JBL PURE BASS POTENTE. O fone de ouvido JBL Tune 530BT entrega graves profundos e impactantes com drivers de 33 mm, proporcionando áudio dinâmico para músicas, vídeos e chamadas ao longo do dia.</li><li>ATÉ 76 HORAS DE BATERIA. O fone de ouvido Bluetooth JBL oferece longa duração para uso contínuo, com carga rápida que garante até 5 horas de reprodução em apenas 5 minutos, ideal para rotinas intensas.</li><li>CHAMADAS CLARAS COM 2 MICROFONES. Dois microfones beamforming captam sua voz com precisão e reduzem ruídos externos, proporcionando conversas nítidas mesmo em ambientes movimentados.</li><li>CONEXÃO MULTIPONTO BLUETOOTH 6.0. Alterne facilmente entre dois dispositivos conectados. O fone de ouvido Bluetooth JBL mantém áudio estável, sincronizado e com menor consumo de energia.</li><li>CONFORTO LEVE E DESIGN DOBRÁVEL. O fone de ouvido JBL conta com almofadas macias e estrutura leve para uso prolongado. Dobrável e prático, acompanha sua rotina com conforto e facilidade de transporte.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Cor": "Preto",
      "Colocação na orelha": "Extra-auriculares",
      "Fator de forma dos fones de ouvido": "Extra-auriculares",
      "Impedância": "20 Ohms"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-Ouvido-Bluetooth-Over-Ear-Bateria/dp/B0GM1LSHQF?ref=dlx_deals_dg_dcl_B0GM1LSHQF_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FPRK5P9H",
    "title": "SEMP, Smart TV 4K UHD, 55“, Google TV, Google Assistente, Comando por Voz, Googlecast Integrado, Design Sem Bordas, Dolby Audio, 55S62",
    "image": "https://m.media-amazon.com/images/I/61mUtpPKNVL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "TVs",
    "price_current": 2099.99,
    "price_original": 2499.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 166,
    "coupon_code": null,
    "description": "<ul><li>Smart TV com Google TV, Wi-Fi Dual Band, Bluetooth, Google Assistente, Dolby Audio, HDMI 2.1, HDR10+ e Googlecast Integrado</li><li>Tela 4K UHD de 55 polegadas com design sem bordas na cor preta, proporcionando imagem de alta resolução e visual moderno</li><li>Controle por comando de voz via Google Assistente para navegação prática entre aplicativos, conteúdos e configurações da TV</li></ul>",
    "informacoes_produto": {
      "Tamanho da tela": "55",
      "Marca": "Semp",
      "Tecnologia do visor": "4K UHD, LCD, OLED, UHD",
      "Resolução": "4K",
      "Taxa de atualização": "60 Hz",
      "Características especiais": "Google Assistente, Dolby Audio, HDMI 2.1, HDR10+, Googlecast Integrado, design sem bordas",
      "Componentes incluídos": "01 Televisor 55\", 01 Controle Remoto, 1 Cabo Adaptador P2/RCA",
      "Tecnologia de conectividade": "HDMI, USB, Wi-fi",
      "Proporção de tela": "16:9",
      "Dimensões do produto": "71,1P x 122,6L x 7,3A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/SEMP-SMART-55S62-UHD-GOOGLE/dp/B0FPRK5P9H?ref=dlx_deals_dg_dcl_B0FPRK5P9H_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=9ZOMT9Jm0JH%2Ft%2BWi68iDSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0CSPRNRZC",
    "title": "MSI GeForce RTX 3050 LP 6G OC (6GB GDDR6/PCI Express 4.0/1492MHz/14000MHz/Perfil baixo)",
    "image": "https://m.media-amazon.com/images/I/71Z9DLS29FL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Placas de Vídeo",
    "price_current": 999.0,
    "price_original": 1641.57,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 873,
    "coupon_code": null,
    "description": "<ul><li>Ventilador duplo: dois ventiladores e um enorme dissipador de calor garantem uma experiência fresca e silenciosa para você.</li><li>MSI Afterburner: o melhor software de overclocking com opções avançadas de controle e monitor de hardware em tempo real.</li><li>PCB personalizado: O PCB personalizado foi projetado com circuitos endurecidos e roteamento de rastreamento otimizado para desempenho e confiabilidade.</li><li>MSI Centro: O software exclusivo MSI Centre permite monitorar, ajustar e otimizar os produtos MSI em tempo real.</li></ul>",
    "informacoes_produto": {
      "Coprocessador gráfico": "NVIDIA GeForce RTX 3050",
      "Marca": "MSI",
      "Tamanho da memória RAM da placa gráfica": "6 GB",
      "Velocidade do clock da GPU": "1492 MHz",
      "Interface de saída de vídeo": "HDMI, DisplayPort"
    },
    "affiliate_url": "https://www.amazon.com.br/MSI-GeForce-Express-1492MHz-14000MHz/dp/B0CSPRNRZC?ref=dlx_deals_dg_dcl_B0CSPRNRZC_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": true
  },
  {
    "asin": "B0D81JTSGX",
    "title": "Lavadora de Roupas 13kg Branca Midea Wave Agitator 127V",
    "image": "https://m.media-amazon.com/images/I/41WaSpk6xDL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Máquinas de Lavar",
    "price_current": 1800.0,
    "price_original": 2199.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 21,
    "coupon_code": null,
    "description": "<ul><li>Lavadora Top Load</li></ul>",
    "informacoes_produto": {
      "Dimensões do produto": "59,6P x 58L x 101,5A centímetros",
      "Marca": "Midea",
      "Capacidade": "13 quilogramas",
      "Características especiais": "Alta eficiência",
      "Local de acesso": "Carga superior"
    },
    "affiliate_url": "https://www.amazon.com.br/Lavadora-Roupas-Branca-Midea-Agitator/dp/B0D81JTSGX?ref=dlx_deals_dg_dcl_B0D81JTSGX_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B000WLN7AM",
    "title": "Whisky Bourbon Maker's Mark 750ml",
    "image": "https://m.media-amazon.com/images/I/7199P9zzMGL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Whisky",
    "price_current": 119.9,
    "price_original": 145.33,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 3369,
    "coupon_code": null,
    "description": "<ul><li>Com coloração âmbar, laranja-amarelada, o bourbon tornou-se um dos destilados mais apreciados no mundo.</li><li>Diferentemente da composição do whisky tradicional, o Maker’s Mark não possui centeio na sua formulação, e sim, trigo doce e vermelho de inverno, milho e cevada.</li><li>O sucesso é fruto de um processo produtivo minucioso, que segue à risca os padrões de qualidade.</li><li>A produção é feita em baixa escala, em lotes individuais que não ultrapassam 19 barris por lote.</li><li>O Maker’s Mark é envelhecido por cerca de seis anos, depois de engarrafado é então selado em uma garrafa de forma única e selada com a cera vermelha na rolha.</li></ul>",
    "informacoes_produto": {
      "Marca": "Maker's Mark",
      "Tipo de álcool": "Bourbon",
      "Sabor": "Chocolate",
      "Contagem de unidades": "750.0 Mililitro",
      "Número de itens": "1"
    },
    "affiliate_url": "https://www.amazon.com.br/Whiskey-MakerS-Mark-Makers-Sabor/dp/B000WLN7AM?ref=dlx_deals_dg_dcl_B000WLN7AM_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FL2QF7YJ",
    "title": "JBL, Caixa de Som, PartyBox Encore Essential 2, Show de Luzes, Bluetooth, Portátil, Resistente a Respingos, Bateria de até 15h, Som JBL Pro Sound, AI Sound Boost, 100 W RMS",
    "image": "https://m.media-amazon.com/images/I/71Ar78y955L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Caixas de Som Portáteis Bluetooth",
    "price_current": 1328.99,
    "price_original": 1899.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 459,
    "coupon_code": null,
    "description": "<ul><li>SOM POTENTE COM AI SOUND BOOST. O JBL Pro Sound ganha ainda mais potência com o AI Sound Boost, oferecendo agudos nítidos e graves impactantes, mesmo em alto volume e ambientes amplos.</li><li>SHOW DE LUZES NO RITMO DA MÚSICA. Os efeitos de luzes dinâmicas criam o clima ideal para qualquer festa, com padrões vibrantes e estroboscópicos que seguem o ritmo da sua playlist do começo ao fim.</li><li>DURAÇÃO PARA O DIA TODO. A bateria integrada oferece até 15 horas de reprodução contínua com uma única carga.</li><li>TECNOLOGIA AURACAST. É possível emparelhar com outro JBL PartyBox Encore Essential 2 ou conectar várias caixas via JBL Auracast para ampliar sua experiência sonora.</li><li>DESIGN RESISTENTE. Com alça prática para transporte e proteção contra respingos (IPX4), a PartyBox Encore Essential 2 está pronta para festas em qualquer ambiente ou clima.</li></ul>",
    "informacoes_produto": {
      "Marca": "JBL",
      "Dimensões do item C x L x A": "29 x 33 x 28 centímetros",
      "Tecnologia de conectividade": "Bluetooth",
      "Cor": "Preto",
      "Dispositivos compatíveis": "Leitor de MP3, Notebook, Smartphone, Tablet"
    },
    "affiliate_url": "https://www.amazon.com.br/JBL-PartyBox-Essential-Bluetooth-Respingos/dp/B0FL2QF7YJ?ref=dlx_deals_dg_dcl_B0FL2QF7YJ_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B07FPW95CM",
    "title": "Jameson - Whiskey Irlandês, 750 ml",
    "image": "https://m.media-amazon.com/images/I/51syfbaTceL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Whisky",
    "price_current": 69.08,
    "price_original": 130.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7085,
    "coupon_code": null,
    "description": "<ul><li>Sabor suave e equilibrado com toque adocicado</li><li>Destilado triplo de alta qualidade</li><li>Ideal para drinks ou puro</li><li>Garrafa elegante e tradicional</li><li>Whiskey irlandês reconhecido mundialmente</li></ul>",
    "informacoes_produto": {
      "Marca": "Jameson",
      "Tipo de álcool": "Blended whiskey",
      "Sabor": "Whisky",
      "Número de itens": "1",
      "Teor alcoólico": "15 %"
    },
    "affiliate_url": "https://www.amazon.com.br/Jameson-Whisky-750ml/dp/B07FPW95CM?ref=dlx_deals_dg_dcl_B07FPW95CM_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B09GSQMVJS",
    "title": "L'Oréal Professionnel Inforcer Shampoo Fortificante Antiqueda por Quebra, Crescimento Saudável Para Cabelos Frágeis e Quebradiços Com Biotina e Vitamina B6, 300ml",
    "image": "https://m.media-amazon.com/images/I/51TvgvfNA9L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Shampoos para Crescimento do Cabelo",
    "price_current": 67.4,
    "price_original": 116.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7268,
    "coupon_code": null,
    "description": "<ul><li>Um tratamento em shampoo que limpa, fortalece e proporciona uma ação anti-quebra instantânea nos fios.</li><li>Enriquecido com Biotina e Vitamina B6, que estimulam o crescimento saudável e o metabolismo de proteínas.</li><li>Leva nutrientes à fibra capilar, promovendo força instantânea e prevenindo o ressecamento e a quebra.</li><li>Com o uso contínuo, os cabelos se tornam mais resistentes, com menos queda e com um crescimento visível.</li><li>Conquiste cabelos suplementados com força, nutridos, resistentes e com o crescimento saudável que você deseja.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Líquido",
      "Tipo de cabelo": "Todos os tipos de cabelos",
      "Aroma": "Sem perfume",
      "Faixa etária (descrição)": "Adulto"
    },
    "affiliate_url": "https://www.amazon.com.br/LOr%C3%A9al-Professionnel-Fortificante-Anti-Quebra-Quebradi%C3%A7os/dp/B09GSQMVJS?ref=dlx_deals_dg_dcl_B09GSQMVJS_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0FJPL1MGY",
    "title": "Samsung Galaxy Watch Ultra 2025 Smartwatch 47mm LTE, Galaxy AI, Titânio Aeroespacial, Titânio Prata",
    "image": "https://m.media-amazon.com/images/I/518YXVYcCRL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Smartwatches",
    "price_current": 2099.0,
    "price_original": 4999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 66,
    "coupon_code": null,
    "description": "<ul><li>Titânio Aeroespacial e resistência</li><li>Até 100m de resistencia a água do mar</li><li>Bateria de até 100h</li><li>GPS duplo de alta precisão</li><li>Treinador de corrida avançado</li></ul>",
    "informacoes_produto": {
      "Sistema operacional": "Galaxy AI",
      "Capacidade de armazenamento da memória": "64 GB",
      "Capacidade da bateria": "590 Milliamp Hours",
      "Tecnologia de conectividade": "Bluetooth, NFC, Wi-Fi"
    },
    "affiliate_url": "https://www.amazon.com.br/Samsung-Galaxy-Watch-Smartwatch-Tit%C3%A2nio/dp/B0FJPL1MGY?ref=dlx_deals_dg_dcl_B0FJPL1MGY_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": true
  },
  {
    "asin": "B0G3CY35DN",
    "title": "Notebook Lenovo IdeaPad Slim 3 15IRU10 Intel Core 3 100U 8GB 256GB SSD Windows 11 15.3\" - 83NU0000BR Luna Grey",
    "image": "https://m.media-amazon.com/images/I/61QqrCnGyfL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Notebooks",
    "price_current": 3399.0,
    "price_original": 1299.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 7,
    "coupon_code": null,
    "description": "<ul><li>Aumente sua produtividade e mobilidade com o IdeaPad Slim 3i</li><li>Tela IPS de 16\" WUXGA (16:10) com imagens nítidas e cores vibrantes</li><li>Gráficos Intel Arc para performance avançada em tarefas criativas</li></ul>",
    "informacoes_produto": {
      "Marca": "Lenovo",
      "Nome do modelo": "IdeaPad Slim 3 15IRU10",
      "Tamanho da tela": "15,3 Polegadas",
      "Cor": "Cinza",
      "Tamanho do disco rígido": "256 GB",
      "Modelo da CPU": "Intel Core 3",
      "Tamanho instalado da memória RAM": "8 GB",
      "Sistema operacional": "Windows 11 Home Single Language",
      "Características especiais": "Áudio HD",
      "Descrição da placa de vídeo": "Integrated Intel Graphics"
    },
    "affiliate_url": "https://www.amazon.com.br/Notebook-Lenovo-IdeaPad-15IRU10-Windows/dp/B0G3CY35DN?ref=dlx_deals_dg_dcl_B0G3CY35DN_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B07X4JG2G4",
    "title": "Duracell Carregador de Pilhas Recarregáveis AA e AAA Com 4 Pilhas AA Inclusas – Bivolt",
    "image": "https://m.media-amazon.com/images/I/819KK4qPMeL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Carregadores de Pilha",
    "price_current": 144.3,
    "price_original": 198.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 62227,
    "coupon_code": null,
    "description": "<ul><li>Auto desligamento quando as pilhas carregam 100%</li><li>Proteção que garante o carregamento seguro</li></ul>",
    "informacoes_produto": {
      "Número de baterias": "4 AA baterias necessárias. (inclusas)",
      "Marca": "Duracell",
      "Composição das células da bateria": "Alcalina",
      "Capacidade da bateria": "2500",
      "Adequação do controle por rádio": "Aparelho auditivo, Controle remoto da TV, Câmera, Drone, Relógio"
    },
    "affiliate_url": "https://www.amazon.com.br/Carregador-Pilhas-com-pilhas-Duracell/dp/B07X4JG2G4?ref=dlx_deals_dg_dcl_B07X4JG2G4_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0D8KXMCTC",
    "title": "GameSir G7 SE Controle com Fio para PC, Xbox One, Xbox Series X|S, Gamepad para Jogos Plug and Play (Laranja)",
    "image": "https://m.media-amazon.com/images/I/51psQhV+vPL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Controles e Gamepads",
    "price_current": 279.0,
    "price_original": 399.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 16444,
    "coupon_code": null,
    "description": "<ul><li>Compatibilidade Ampla para Xbox e PC：Compatível com Xbox Series X|S, Xbox One X/S e PC com Windows 10/11, incluindo suporte para jogos no Steam. Ideal para gamers que buscam um controle versátil e confiável.</li><li>Precisão Superior com Hall Effect：Equipado com joysticks e gatilhos com tecnologia Hall Effect, oferecendo maior precisão, resposta rápida e vida útil prolongada, eliminando problemas de drift.</li><li>Conexão com Fio Plug and Play：Controle com fio USB removível, fácil de usar, sem necessidade de drivers. Basta conectar e jogar instantaneamente no Xbox ou PC.</li><li>Botões Traseiros Programáveis：Conta com 2 botões traseiros personalizáveis, permitindo ajustes rápidos para melhorar o desempenho e evitar comandos incorretos durante o jogo.</li><li>Experiência Imersiva e Confortável：Motores de vibração assimétrica e gatilhos com feedback tátil proporcionam maior imersão. Entrada P2 3,5mm para fones de ouvido e design ergonômico com textura antiderrapante garantem conforto durante longas sessões.</li><li>Improved audio and comfort: equipped with a 3.5 mm audio interface for seamless connection with gaming headsets and an ergonomic handle with ultra-fine laser-engraved texture for comfortable and non-slip gaming sessions.</li></ul>",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Controle-GameSir-Effect-Mec%C3%A2nicos-Laranja/dp/B0D8KXMCTC?ref=dlx_deals_dg_dcl_B0D8KXMCTC_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B09JCQLC7D",
    "title": "Oikos - Kit 10 Potes de Vidro Herméticos 250ml Redondos com Tampa Bambu | Borossilicato, vedação em silicone, BPA Free, mantimentos, empilháveis, fácil limpeza, design natural",
    "image": "https://m.media-amazon.com/images/I/616-Dra0CyL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Organizadores e Armazenamento",
    "price_current": 84.55,
    "price_original": 202.97,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 2973,
    "coupon_code": null,
    "description": "<ul><li>Cabe em qualquer lugar: seu formato redondo ajuda a aproveitar melhor o espaço</li><li>Tampa hermética: sua tampa possui um anel de vedação de silicone que veda de verdade!</li><li>Mestre da conservação: a combinação da vedação de silicone com o bambu antibacteriano garante melhor conservação dos alimentos que duram por muito mais tempo.</li></ul>",
    "informacoes_produto": {
      "Marca": "OIKOS",
      "Cor": "Natural",
      "Material": "Bambu, Vidro",
      "Característica do material": "Seguro para forno, Seguro para micro-ondas, Antibacteriano",
      "Capacidade": "250 ml"
    },
    "affiliate_url": "https://www.amazon.com.br/Potes-Vidro-Redondo-250ML-Tampa/dp/B09JCQLC7D?ref=dlx_deals_dg_dcl_B09JCQLC7D_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0G1FMS7DQ",
    "title": "M-VAVE MK-300 Modelador de Amp e Efeitos para Guitarra/Baixo com Looper, Drum Machine, Bluetooth, 11 Módulos, 160 Presets, Pedal de Expressão, USB-C, Ideal para Estúdio e Palco",
    "image": "https://m.media-amazon.com/images/I/61VhpFNh1uL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Guitarra Acústica",
    "price_current": 854.13,
    "price_original": 999.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 3,
    "coupon_code": null,
    "description": "<ul><li>Com 120 modelos de amplificador baseados em tecnologia ANN e 100 cabines com suporte a arquivos IR de terceiros, o MK-300 reproduz fielmente o som de amplificadores a válvula para guitarra, baixo e violão acústico, ideal para diversos estilos musicais.</li><li>Explore 11 módulos de efeitos com mais de 320 tipos, incluindo wah, modulação, delay e reverb, para personalizar totalmente seu timbre e criar sons únicos para performances ao vivo ou gravações em estúdio.</li><li>Looper integrado com 301.7 segundos de gravação e máquina de bateria com 128 padrões rítmicos permitem praticar e compor com facilidade, com sincronização opcional e salvamento automático de ideias.</li><li>Conectividade avançada inclui entrada MIDI, saídas XLR balanceadas, USB-C para interface de áudio, gravação OTG e Bluetooth para streaming de música e controle via app, garantindo versatilidade.</li><li>Bateria de longa duração com até 10 horas de uso contínuo e 4 footswitches personalizáveis oferecem controle intuitivo para mudar presets e ajustar parâmetros rapidamente em performances.</li></ul>",
    "informacoes_produto": {
      "Marca": "M-VAVE",
      "Dimensões do produto": "38C x 9L x 21A centímetros",
      "Peso do produto": "1800 Gramas"
    },
    "affiliate_url": "https://www.amazon.com.br/M-VAVE-MK-300-Modelador-Bluetooth-Express%C3%A3o/dp/B0G1FMS7DQ?ref=dlx_deals_dg_dcl_B0G1FMS7DQ_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B082481SDH",
    "title": "Cápsulas de Café Original Nespresso Variados - 50 Cápsulas",
    "image": "https://m.media-amazon.com/images/I/51BwrtdepjL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Cápsulas de Café",
    "price_current": 157.25,
    "price_original": 170.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 461,
    "coupon_code": null,
    "description": "<ul><li>Uma variedade de sabores perfeitamente equilibrados: Volluto (x 10 capsulas), Ispirazione Genova Livanto (x 10 capsulas), Ispirazione Ristretto Italiano (x 10 capsulas), Ispirazione Roma (x 10 capsulas) e Firenze Arpeggio (x 10 capsulas)</li><li>Café fresco e suave em um instante: recrie aquele sabor rico e luxuoso de cafeteria com a tecnologia de cápsula de café original da NESPRESSO</li><li>Café NESPRESSO 100% original: em uma variedade de deliciosos sabores aromáticos. Cada cápsula individual é lacrada e pronta para uso em sua máquina</li><li>Café de origem responsável: nos dedicamos à qualidade e sustentabilidade, para um sabor requintado em cada xícara</li></ul>",
    "informacoes_produto": {
      "Marca": "Nespresso",
      "Forma do produto": "Cápsula",
      "Descrição do teor de cafeína": "Com cafeína",
      "Nível de torragem": "Torra média"
    },
    "affiliate_url": "https://www.amazon.com.br/Nespresso-50-c%C3%A1psulas-caf%C3%A9-Variado/dp/B082481SDH?ref=dlx_deals_dg_dcl_B082481SDH_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0B7SH8YPV",
    "title": "L'Oréal Professionnel NutriOil Leave-in, Hidratação e Nutrição Intensa para Cabelos Secos e Sem Brilho, com Óleo de Coco, Proteção Térmica e Antifrizz, 150ml",
    "image": "https://m.media-amazon.com/images/I/41YAXDAgkVL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Cremes e Loções",
    "price_current": 104.39,
    "price_original": 159.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 2170,
    "coupon_code": null,
    "description": "<ul><li>Este leave-in profissional é a solução ideal para cabelos secos e sem brilho, proporcionando nutrição profunda sem pesar os fios, ideal para complementar seu cronograma capilar.</li><li>Sua fórmula avançada é enriquecida com 1,5% de óleo de coco, que oferece ação umectante, fortalecendo a resistência da fibra capilar e promovendo maciez, brilho e movimento.</li><li>Desfrute de proteção térmica de até 230°C, protegendo os cabelos do calor de ferramentas e garantindo proteção antifrizz por até 24 horas.</li><li>Com sua ação umectante, o óleo de coco adere ao fio formando uma camada protetora na superfície Além de penetrar na fibra, fortalecendo a sua resistência e promovendo nutrição com maciez, brilho e movimento.</li><li>Contém: 1 Leave-in L'Oréal Professionnel NutriOil 150ml, para cabelos instantaneamente 4x mais macios e com muito mais brilho.</li></ul>",
    "informacoes_produto": {
      "Marca": "L'Oréal Professionnel Paris",
      "Forma do produto": "Líquido",
      "Característica do material": "Sustentável",
      "Tipo de cabelo": "Seco",
      "Vantagens do produto": "Nutritivo"
    },
    "affiliate_url": "https://www.amazon.com.br/LOREAL-PROFESSIONNEL-NutriOil-nutri%C3%A7%C3%A3o-enriquecido/dp/B0B7SH8YPV?ref=dlx_deals_dg_dcl_B0B7SH8YPV_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "8501116432",
    "title": "A paciente silenciosa",
    "image": "https://m.media-amazon.com/images/I/91R8S52UP6L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Europeia",
    "price_current": 37.78,
    "price_original": 64.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 52017,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/paciente-silenciosa-Alex-Michaelides/dp/8501116432?ref=dlx_deals_dg_dcl_8501116432_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0977SH2WT",
    "title": "NexGard SPECTRA Antipulgas e Vermífugo para Cães de 30,1 a 60kg - 1 tablete",
    "image": "https://m.media-amazon.com/images/I/61QSedOZ-2L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Gotas de pulgas",
    "price_current": 101.55,
    "price_original": 190.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 4318,
    "coupon_code": null,
    "description": "<ul><li>O tablete mais completo do mercado*, indicado para proteção contra pulgas, carrapatos (incluindo o carrapato estrela), ácaros da sarna otodécica, demodécica e sarcóptica, vermes intestinais e prevenção do verme do coração.</li><li>Tablete mastigável sabor carne, preferido por 9 em cada 10 cães¹.</li><li>Indicado para cães a partir de 8 semanas de vida e 2kg.</li><li>Ação rápida e segura para todas as raças.</li><li>Pode ser administrado com ou sem alimento.</li></ul>",
    "informacoes_produto": {
      "Marca": "Nexgard",
      "Forma do produto": "Tablete",
      "Aroma": "Carne",
      "Ingredientes ativos": "Afoxolaner e Milbemicina Oxima",
      "Volume do produto": "240 Centímetros cúbicos"
    },
    "affiliate_url": "https://www.amazon.com.br/Nexgard-Spectra-Antipulgas-Carrapatos-Marrom/dp/B0977SH2WT?ref=dlx_deals_dg_dcl_B0977SH2WT_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "6555658479",
    "title": "A última carta",
    "image": "https://m.media-amazon.com/images/I/81NjNkmjBqL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Literatura de Gênero",
    "price_current": 46.85,
    "price_original": 79.9,
    "parcelamento": "Em até 12x de R$ 4,33 com juros Ver opções de pagamento",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 2711,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/%C3%BAltima-carta-Rebecca-Yarros/dp/6555658479?ref=dlx_deals_dg_dcl_6555658479_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B076HYZQMW",
    "title": "ELG, PWC-R5, PowerCube, Multiplicador 5 Tomadas, Disjuntor Integrado de 10A, Filtro de Linha com Protetor de Surto, Bivolt, Branco e Verde",
    "image": "https://m.media-amazon.com/images/I/51CsZOBHOoL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Filtros de Linha",
    "price_current": 50.0,
    "price_original": 91.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5348,
    "coupon_code": null,
    "description": "<ul><li>MULTIPLICADOR DE TOMADAS: Compacto, e em formato de cubo, o PowerCube transforma uma única tomada em 5 pontos de energia, que podem ser utilizadas simultaneamente para carregamento rápido de dispositivos eletrônicos.</li><li>TRAVA PARA CRIANÇAS: O sistema Child Lock garante proteção extra ao impedir a inserção acidental de objetos nas tomadas, liberando a entrada apenas quando os pinos são inseridos simultaneamente.</li><li>DESIGN PREMIADO: Com design premiado internacionalmente, sua estrutura única permite conectar todos os plugues ao mesmo tempo, sem bloqueios entre si. É ideal para uso em residências, escritórios e hotéis.</li><li>QUALIDADE PREMIUM: Fabricado em policarbonato antichamas, com conectores em cobre de alta pureza e certificação pelo Inmetro, obtenha segurança e eficiência em um produto bivolt de alto padrão.</li><li>SOBRE A ELG: A ELG é uma empresa brasileira que preza pela alta qualidade. Nossa política é aplicada em toda linha de produtos e garante que os consumidores possam adquirir itens que foram amplamente testados.</li></ul>",
    "informacoes_produto": {
      "Marca": "ELG",
      "Cor": "Verde e Branco",
      "Total de tomadas de energia": "5",
      "Tensão": "110 Volts, 220 Volts",
      "Características especiais": "Proteção de sobretensão"
    },
    "affiliate_url": "https://www.amazon.com.br/Multiplicador-Tomadas-PowerCube-Elg-PWC-R5/dp/B076HYZQMW?ref=dlx_deals_dg_dcl_B076HYZQMW_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "8542229177",
    "title": "Tempestade de Ônix: Sequência dos fenômenos mundiais Quarta Asa e Chama de Ferro (Série O Empyriano, Livro 3)",
    "image": "https://m.media-amazon.com/images/I/91915km0UdL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Paranormal",
    "price_current": 69.64,
    "price_original": 109.9,
    "parcelamento": "Em até 12x de R$ 6,43 com juros Ver opções de pagamento",
    "tem_selo_prime": false,
    "avaliacao": 4.8,
    "qtd_avaliacoes": 7694,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Tempestade-%C3%94nix-Sequ%C3%AAncia-fen%C3%B4menos-Empyriano/dp/8542229177?ref=dlx_deals_dg_dcl_8542229177_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H1HPNBK6",
    "title": "Mstail Bebedouro para gatos sem fio, 3,2 L (113 oz), para uso interno, alimentado por bateria, com sensor de movimento, bomba ultrassilenciosa, livre de BPA Bebedouro Automático para Gatos, 3,2L",
    "image": "https://m.media-amazon.com/images/I/71zSdpc+cFL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Fontes",
    "price_current": 174.99,
    "price_original": 199.99,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 27,
    "coupon_code": null,
    "description": "<ul><li>【Bebedouro para gatos sem fio】Com reservatório de 3,2 litros, este bebedouro para gatos sem fio mantém seu gato hidratado por dias, ideal para proprietários que passam horas fora. Seu design sem fios, sem necessidade de tomadas, permite instalação em qualquer lugar da casa ou ao ar livre, eliminando riscos de mordedura de fios e garantindo segurança total</li><li>【Bateria de Longa Duração Até 60 Dias com Uma Única Carga】 Este bebedouro para gatos com uma bateria de lítio recarregável de 4000 mAh, oferecendo uma autonomia impressionante de até 60 dias em modo de espera. Reduz drasticamente a necessidade de recargas frequentes e funciona mesmo sem energia elétrica, mantendo seu pet hidratado durante viagens ou interrupções de luz</li><li>【3 Modos de Fluxo Adaptados aos Hábitos do Seu Gato】 Oferece três modos de operação, atendendo aos diferentes gostos e necessidades de beber do seu felino: ① Modo de Indução: Quando o pet se aproxima até 1,5 metros do aparelho, o fluxo de água é ativado automaticamente e dura 15 segundos. ② Modo Intermitente: O fluxo é iniciado por 20 segundos a cada intervalo de 20 minutos, estimulando a hidratação. ③ Modo Contínuo: Mantém o fluxo constante quando conectado à fonte de energia elétrica</li><li>【Bomba Silenciosa e Design Econômico em Energia】 Equipado com uma bomba ultrassilenciosa (≤30 decibéis), Não assusta os gatos tímidos nem perturba o sono noturno. Com o design econômico de 5V 1A, combina baixo consumo de energia com performance eficiente, mantendo o ruído no mínimo</li><li>【Sistema de Filtragem Avançado para Água Pura】 O reservatório de água filtrada para gatos integra um sistema de multifiltragem de 3 camadas, com filtros de carvão ativado. Essa tecnologia captura pelos, detritos e remove impurezas, garantindo que seu gato consuma apenas água limpa e fresca em cada gole</li></ul>",
    "informacoes_produto": {
      "Cor": "Branco",
      "Material": "304 Aço inoxidável, Plástico",
      "Marca": "Mstail",
      "Capacidade": "3,2 litros",
      "Contagem de unidades": "3.2 litro(s)"
    },
    "affiliate_url": "https://www.amazon.com.br/Mstail-Bebedouro-alimentado-ultrassilenciosa-Autom%C3%A1tico/dp/B0H1HPNBK6?ref=dlx_deals_dg_dcl_B0H1HPNBK6_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B07B84G8WX",
    "title": "Hamilton Beach, 80393-BZ127, Moedor Ajustável , 127V, Preto",
    "image": "https://m.media-amazon.com/images/I/71byJunyuJL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Acessórios para Cafeteiras",
    "price_current": 284.05,
    "price_original": 349.0,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.7,
    "qtd_avaliacoes": 5854,
    "coupon_code": null,
    "description": "<ul><li>127v</li><li>Funciona automaticamente sem precisar das mãos</li><li>5 níveis de moagem</li><li>Preto</li><li>Fabricante: Hamilton Beach</li><li>Nota:O moedor tem uma trava de segurança na tampa. Certifique-se de fechar a tampa corretamente e gire-a até ouvir o “clique”, para ligar o produto</li></ul>",
    "informacoes_produto": {
      "Cor": "Preta",
      "Marca": "Hamilton Beach",
      "Material": "Aço inoxidável, Plástico",
      "Estilo": "Moderno",
      "Dimensões do produto": "11,9C x 11,3L x 20,4A centímetros"
    },
    "affiliate_url": "https://www.amazon.com.br/Ajust%C3%A1vel-Hamilton-Beach-80393-BZ127-Pequeno/dp/B07B84G8WX?ref=dlx_deals_dg_dcl_B07B84G8WX_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "8543111536",
    "title": "Murdoku: 80 mistérios para resolver usando a lógica",
    "image": "https://m.media-amazon.com/images/I/81BZuXOk+7L._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Mistério",
    "price_current": 37.4,
    "price_original": 59.9,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 4.9,
    "qtd_avaliacoes": 1216,
    "coupon_code": null,
    "description": "",
    "informacoes_produto": {},
    "affiliate_url": "https://www.amazon.com.br/Murdoku-mist%C3%A9rios-resolver-usando-l%C3%B3gica/dp/8543111536?ref=dlx_deals_dg_dcl_8543111536_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  },
  {
    "asin": "B0H37C1TWT",
    "title": "Cadeira Gamer Husky Storm 100, Até 120kg, Almofadas, Reclinável 135º, PU, Preta - HCG100PT",
    "image": "https://m.media-amazon.com/images/I/41JUn0JDieL._AC_SL1500_.jpg?aicid=discounts-widgets-horizonte",
    "canonical": null,
    "category": "Cadeiras Gamer",
    "price_current": 367.99,
    "price_original": 444.43,
    "parcelamento": null,
    "tem_selo_prime": false,
    "avaliacao": 5.0,
    "qtd_avaliacoes": 3,
    "coupon_code": null,
    "description": "<ul><li>cadeira gamer barata inicial custo beneficio couro preto almofada</li><li>Design ergonômico: Possui braços linkage que se ajustam automaticamente ao reclinar o encosto, mantendo o suporte ideal aos antebraços.</li><li>Material de : A tapeçaria em PU é agradável ao toque e fácil de limpar, garantindo durabilidade e conforto.</li></ul>",
    "informacoes_produto": {
      "Marca": "Husky",
      "Cor": "Preto",
      "Material": "PU",
      "Tamanho": "50 x 50 x 52 cm",
      "Contagem de unidades": "1 Count"
    },
    "affiliate_url": "https://www.amazon.com.br/Cadeira-Gamer-Husky-Almofadas-Reclin%C3%A1vel/dp/B0H37C1TWT?ref=dlx_deals_dg_dcl_B0H37C1TWT_dt_sl14_88_pi&pf_rd_r=RGRQCWZ9T6ZHEYP5NKXS&pf_rd_p=a43a02c5-fe2d-4a34-af71-7d62fff70488&tag=mixdm22-20",
    "last_checked_at": "2026-07-17T00:28:08.000Z",
    "spotlight": false
  }
];
